/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.Attendance;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.smsc.controller1.Attendance_Contorller;
import com.smsc.Controller.Calculeshan.Attendance_Calculation;
import com.smsc.controller1.Empolyee_Controller;
import com.smsc.controller1.Grade_Controller;
import com.smsc.model.Attendance;
import com.smsc.model.Employee;
import com.smsc.model.getattendance_byemployee_nic;
import com.smsc.other.IdGenerator;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author smsc
 */
public class Mark_Attendance extends javax.swing.JFrame {
    private Search_Attendance search_Attendance=null;
    private Empolyee_Controller empolyee_Controller;
    private Attendance_Contorller attendance_Contorller;
    private Grade_Controller grade_Controller;
    private String Atid;
    private int timeRun=0;
    private String time1=null;
    private DefaultComboBoxModel dcbm;
    private DefaultComboBoxModel dcbm1;
    int xmouse;
    int ymouse;
    /**
     * Creates new form Mark_Attendance
     */
    public Mark_Attendance() {
        initComponents();
        empolyee_Controller=new Empolyee_Controller();
        attendance_Contorller=new Attendance_Contorller();
        grade_Controller=new Grade_Controller();
        setLocationRelativeTo(null);
        setDate();
        setTime();
        Textattendanceid1.setText(" ");
         try {
             loadEmployeeNIC();
             setid();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formatedDate = dateFormat.format(date);
        Texdate.setText(formatedDate);
    }
    private void setid() throws ClassNotFoundException, SQLException{
        String newId = IdGenerator.getNewId("Attendance", "Atid", "A");
       Textattendanceid1.setText(newId);
    }
        private void setTime(){
        new Thread()
        {
            @Override
            public void run()
            {
                while(timeRun==0){
                    Calendar cal=new GregorianCalendar();
                    int AM_PM=cal.get(Calendar.AM_PM);
                    String day="";
                    if(AM_PM==1)
                    {
                    day="PM";
                    }
                    else 
                    {
                        day="AM";
                    }
                    Date d=new Date();
                    SimpleDateFormat dateFormat1=new SimpleDateFormat("HH:mm:ss:aa");
                    String format1 = dateFormat1.format(d);
                    labTime.setText(format1);
                    time1=format1;
                    if (day.equals("AM")) {
                        btGetArrivalTime.setEnabled(true);
                        btLeaveTime.setEnabled(false);
                    } else {
                        btLeaveTime.setEnabled(true);
                        btGetArrivalTime.setEnabled(false);
                    }
                    }
               }
         }.start();
    }
    public void loadEmployeeNIC() throws ClassNotFoundException, SQLException{
        dcbm=(DefaultComboBoxModel) ComboEmployeeNic.getModel();
        dcbm1=(DefaultComboBoxModel) ComboEmployeeNic1.getModel();
        dcbm.removeAllElements();
        dcbm.addElement("");
        dcbm1.removeAllElements();
        dcbm1.addElement("");
        ArrayList<Employee> _all_Employee = empolyee_Controller.get_all_Employee();
        for(Employee employee:_all_Employee){
            dcbm.addElement(employee.getNic_No());
            AutoCompleteDecorator.decorate(ComboEmployeeNic);
            dcbm1.addElement(employee.getNic_No());
            AutoCompleteDecorator.decorate(ComboEmployeeNic1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Labelemployeeid1 = new javax.swing.JLabel();
        ComboEmployeeNic1 = new javax.swing.JComboBox();
        Labelattend1 = new javax.swing.JLabel();
        Labelarrivaltime1 = new javax.swing.JLabel();
        TextArrivaltime1 = new javax.swing.JTextField();
        Labelleavetime = new javax.swing.JLabel();
        TextLeavetime = new javax.swing.JTextField();
        btLeaveTime = new javax.swing.JButton();
        TextOtamount = new javax.swing.JTextField();
        Labelotamount = new javax.swing.JLabel();
        BtAddattendance1 = new javax.swing.JButton();
        texAttend = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Labelemployeeid = new javax.swing.JLabel();
        ComboEmployeeNic = new javax.swing.JComboBox();
        Labelattend = new javax.swing.JLabel();
        ComboEmployeeAttend = new javax.swing.JComboBox();
        Labelarrivaltime = new javax.swing.JLabel();
        TextArrivaltime = new javax.swing.JTextField();
        btGetArrivalTime = new javax.swing.JButton();
        BtAddattendance = new javax.swing.JButton();
        labDateType = new javax.swing.JLabel();
        CheckBoxholiday = new javax.swing.JCheckBox();
        Texdate = new javax.swing.JTextField();
        BtsearchAttendance = new javax.swing.JButton();
        Labelattendanceid1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labDate = new javax.swing.JLabel();
        Textattendanceid1 = new javax.swing.JTextField();
        labTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        btmini = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mark Attendance");
        setMinimumSize(new java.awt.Dimension(1190, 630));
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1190, 630));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1190, 630));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1190, 630));
        jPanel3.setMinimumSize(new java.awt.Dimension(1190, 630));
        jPanel3.setPreferredSize(new java.awt.Dimension(1190, 630));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 1, 2));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Labelemployeeid1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelemployeeid1.setForeground(new java.awt.Color(0, 0, 102));
        Labelemployeeid1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelemployeeid1.setText("Employee Nic  : ");
        jPanel4.add(Labelemployeeid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, 170, 30));

        ComboEmployeeNic1.setEditable(true);
        ComboEmployeeNic1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboEmployeeNic1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ComboEmployeeNic1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboEmployeeNic1ItemStateChanged(evt);
            }
        });
        jPanel4.add(ComboEmployeeNic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 250, 40));

        Labelattend1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelattend1.setForeground(new java.awt.Color(0, 0, 102));
        Labelattend1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelattend1.setText("Attend  : ");
        jPanel4.add(Labelattend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 69, 100, 40));

        Labelarrivaltime1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelarrivaltime1.setForeground(new java.awt.Color(0, 0, 102));
        Labelarrivaltime1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelarrivaltime1.setText("Arrival Time  : ");
        jPanel4.add(Labelarrivaltime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 40));

        TextArrivaltime1.setEditable(false);
        TextArrivaltime1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextArrivaltime1.setForeground(new java.awt.Color(0, 0, 102));
        TextArrivaltime1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(TextArrivaltime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 80, 40));

        Labelleavetime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelleavetime.setForeground(new java.awt.Color(0, 0, 102));
        Labelleavetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelleavetime.setText("Leave Time  : ");
        jPanel4.add(Labelleavetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 40));

        TextLeavetime.setEditable(false);
        TextLeavetime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextLeavetime.setForeground(new java.awt.Color(0, 0, 102));
        TextLeavetime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(TextLeavetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 40));

        btLeaveTime.setBackground(new java.awt.Color(102, 102, 102));
        btLeaveTime.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btLeaveTime.setText("Get Time");
        btLeaveTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLeaveTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLeaveTimeActionPerformed(evt);
            }
        });
        jPanel4.add(btLeaveTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, 40));

        TextOtamount.setEditable(false);
        TextOtamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextOtamount.setForeground(new java.awt.Color(0, 0, 102));
        TextOtamount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(TextOtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, 40));

        Labelotamount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelotamount.setForeground(new java.awt.Color(0, 0, 102));
        Labelotamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelotamount.setText("Ot Amount  : ");
        jPanel4.add(Labelotamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        BtAddattendance1.setBackground(new java.awt.Color(102, 102, 102));
        BtAddattendance1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtAddattendance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/accept.png"))); // NOI18N
        BtAddattendance1.setText("Mark Attendance");
        BtAddattendance1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtAddattendance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddattendance1ActionPerformed(evt);
            }
        });
        jPanel4.add(BtAddattendance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 190, 50));

        texAttend.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texAttend.setForeground(new java.awt.Color(0, 0, 102));
        jPanel4.add(texAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 69, 134, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 570, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 1, 2));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Labelemployeeid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelemployeeid.setForeground(new java.awt.Color(0, 0, 102));
        Labelemployeeid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelemployeeid.setText("Employee Nic  : ");
        jPanel2.add(Labelemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 71, 170, 40));

        ComboEmployeeNic.setEditable(true);
        ComboEmployeeNic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboEmployeeNic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(ComboEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 71, 213, 40));

        Labelattend.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelattend.setForeground(new java.awt.Color(0, 0, 102));
        Labelattend.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelattend.setText("Attend  :  ");
        jPanel2.add(Labelattend, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, 40));

        ComboEmployeeAttend.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboEmployeeAttend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Present", "Absent" }));
        ComboEmployeeAttend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboEmployeeAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEmployeeAttendActionPerformed(evt);
            }
        });
        jPanel2.add(ComboEmployeeAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 159, 40));

        Labelarrivaltime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelarrivaltime.setForeground(new java.awt.Color(0, 0, 102));
        Labelarrivaltime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelarrivaltime.setText("Arrival Time  : ");
        jPanel2.add(Labelarrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 40));

        TextArrivaltime.setEditable(false);
        TextArrivaltime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextArrivaltime.setForeground(new java.awt.Color(0, 0, 102));
        TextArrivaltime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(TextArrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 123, 40));

        btGetArrivalTime.setBackground(new java.awt.Color(102, 102, 102));
        btGetArrivalTime.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btGetArrivalTime.setText("Get Time");
        btGetArrivalTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGetArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetArrivalTimeActionPerformed(evt);
            }
        });
        jPanel2.add(btGetArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 90, 40));

        BtAddattendance.setBackground(new java.awt.Color(102, 102, 102));
        BtAddattendance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtAddattendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/accept.png"))); // NOI18N
        BtAddattendance.setText("Mark Attendance");
        BtAddattendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtAddattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddattendanceActionPerformed(evt);
            }
        });
        jPanel2.add(BtAddattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, 50));

        labDateType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labDateType.setForeground(new java.awt.Color(0, 0, 102));
        labDateType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labDateType.setText("Date Type  : ");
        jPanel2.add(labDateType, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 25, -1, -1));

        CheckBoxholiday.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CheckBoxholiday.setForeground(new java.awt.Color(0, 0, 102));
        CheckBoxholiday.setText("Holiday");
        CheckBoxholiday.setContentAreaFilled(false);
        jPanel2.add(CheckBoxholiday, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 25, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 540, 300));

        Texdate.setEditable(false);
        Texdate.setBackground(new java.awt.Color(0, 153, 204));
        Texdate.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jPanel3.add(Texdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 140, 40));

        BtsearchAttendance.setBackground(new java.awt.Color(102, 102, 102));
        BtsearchAttendance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtsearchAttendance.setText("Search Past Attendance");
        BtsearchAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtsearchAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtsearchAttendanceActionPerformed(evt);
            }
        });
        jPanel3.add(BtsearchAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 40));

        Labelattendanceid1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelattendanceid1.setForeground(new java.awt.Color(0, 0, 102));
        Labelattendanceid1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelattendanceid1.setText("Attendance id  : ");
        jPanel3.add(Labelattendanceid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1190, 10));

        labDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labDate.setForeground(new java.awt.Color(0, 0, 102));
        labDate.setText("Date  : ");
        jPanel3.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, 40));

        Textattendanceid1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.add(Textattendanceid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 100, 30));

        labTime.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labTime.setForeground(new java.awt.Color(0, 0, 102));
        labTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(labTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 430, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Mark Employee Attendance");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btExit.setText("X");
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExitMouseClicked(evt);
            }
        });
        jPanel3.add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));

        btmini.setText("_");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        jPanel3.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SMSC Payroll");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1190, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 210, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 648));

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtsearchAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtsearchAttendanceActionPerformed
        visitToSearch();
    }//GEN-LAST:event_BtsearchAttendanceActionPerformed

    private void BtAddattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddattendanceActionPerformed
    markattendanceInmorning();
    }//GEN-LAST:event_BtAddattendanceActionPerformed

    private void btGetArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetArrivalTimeActionPerformed
        if (time1 != null) {
            TextArrivaltime.setText(time1);
        } else {
            btGetArrivalTime.setCursor(new Cursor(WAIT_CURSOR));
        }
    }//GEN-LAST:event_btGetArrivalTimeActionPerformed

    private void btLeaveTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLeaveTimeActionPerformed
        getOTandleave();
    }//GEN-LAST:event_btLeaveTimeActionPerformed

    private void ComboEmployeeAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEmployeeAttendActionPerformed
        getAMPM();
    }//GEN-LAST:event_ComboEmployeeAttendActionPerformed

    private void BtAddattendance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddattendance1ActionPerformed
        updateTodayattendance();
    }//GEN-LAST:event_BtAddattendance1ActionPerformed

    private void ComboEmployeeNic1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboEmployeeNic1ItemStateChanged
        searchTOupdate();
    }//GEN-LAST:event_ComboEmployeeNic1ItemStateChanged

    private void btExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_btExitMouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        this.setState(Mark_Attendance.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mark_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mark_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mark_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mark_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mark_Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddattendance;
    private javax.swing.JButton BtAddattendance1;
    private javax.swing.JButton BtsearchAttendance;
    private javax.swing.JCheckBox CheckBoxholiday;
    private javax.swing.JComboBox ComboEmployeeAttend;
    private javax.swing.JComboBox ComboEmployeeNic;
    private javax.swing.JComboBox ComboEmployeeNic1;
    private javax.swing.JLabel Labelarrivaltime;
    private javax.swing.JLabel Labelarrivaltime1;
    private javax.swing.JLabel Labelattend;
    private javax.swing.JLabel Labelattend1;
    private javax.swing.JLabel Labelattendanceid1;
    private javax.swing.JLabel Labelemployeeid;
    private javax.swing.JLabel Labelemployeeid1;
    private javax.swing.JLabel Labelleavetime;
    private javax.swing.JLabel Labelotamount;
    private javax.swing.JTextField Texdate;
    private javax.swing.JTextField TextArrivaltime;
    private javax.swing.JTextField TextArrivaltime1;
    private javax.swing.JTextField TextLeavetime;
    private javax.swing.JTextField TextOtamount;
    private javax.swing.JTextField Textattendanceid1;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btGetArrivalTime;
    private javax.swing.JButton btLeaveTime;
    private javax.swing.JButton btmini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDateType;
    private javax.swing.JLabel labTime;
    private javax.swing.JTextField texAttend;
    // End of variables declaration//GEN-END:variables

    private void visitToSearch() {
                if (search_Attendance==null) {
            search_Attendance=new Search_Attendance();
            search_Attendance.setVisible(true);
        } else {
            search_Attendance.setVisible(true);
        }
    }

    private void markattendanceInmorning() {
        String id = Textattendanceid1.getText();
        String employeenic=String.valueOf(ComboEmployeeNic.getSelectedItem());
        String date=Texdate.getText();
        String DateType;
        if (CheckBoxholiday.isSelected()) {
            DateType="Holiday";
        } else {
            DateType="null";
        }
        String attend=String.valueOf(ComboEmployeeAttend.getSelectedItem());
        String arrivaltime=TextArrivaltime.getText();
        String hour = Arrays.toString(arrivaltime.split(":",0));
        try {
            int mark_attendance_in_morning = new Attendance_Calculation().mark_attendance_in_morning(id, employeenic, date, DateType, attend, hour);
            if(mark_attendance_in_morning !=10 && mark_attendance_in_morning ==1){
                JOptionPane.showMessageDialog(this, "Attendance Mark success !!!");
                TextArrivaltime.setText("");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Attendance Mark Fail !!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getOTandleave() {
        if (time1 != null) {
            TextLeavetime.setText(time1);
        } else {
            btLeaveTime.setCursor(new Cursor(WAIT_CURSOR));
        }
        if (TextLeavetime.getText() != null) {
            String hour = Arrays.toString(TextLeavetime.getText().split(":", 0));
            try {
                String _Attendance_ID = new Attendance_Calculation().get_Attendance_ID(String.valueOf(ComboEmployeeNic1.getSelectedItem()), Texdate.getText());
                double Create_OT_Bonus = new Attendance_Calculation().Create_OT_Bonus(_Attendance_ID, hour, String.valueOf(ComboEmployeeNic1.getSelectedItem()));
                if (Create_OT_Bonus != 0.0 && Create_OT_Bonus != 10.0 && Create_OT_Bonus != 100.0) {
                    TextOtamount.setText(String.valueOf(Create_OT_Bonus));
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "No OT Bonus to Calculate !!!");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Error in get time !!!");
        }
    }

    private void getAMPM() {
        String attend=ComboEmployeeAttend.getSelectedItem().toString();
        if (attend.equals("Absent")) {
            btGetArrivalTime.setEnabled(false);
            btLeaveTime.setEnabled(false);
        } else {
            btGetArrivalTime.setEnabled(true);
            btLeaveTime.setEnabled(true);
        }
    }

    private void updateTodayattendance() {
        try {
            String leavetime = TextLeavetime.getText();
            double otamount = Double.parseDouble(TextOtamount.getText());
            Attendance attendance=new Attendance(leavetime,otamount);
            int update_Attendance_LeaveTome_Ot = Attendance_Contorller.update_Attendance_LeaveTome_Ot(attendance);
            if (update_Attendance_LeaveTome_Ot > 0) {
                JOptionPane.showMessageDialog(this, "Attendance Update Scuccess !!!");
                TextArrivaltime1.setText("");
                TextLeavetime.setText("");
                TextOtamount.setText("");
                texAttend.setText("");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Attendance Update Fail !!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchTOupdate() {
        try {
            Employee Search_Employee_by_Nic = empolyee_Controller.Search_Employee_by_Nic(ComboEmployeeNic1.getSelectedItem().toString());
            if (Search_Employee_by_Nic != null) {
                ArrayList<getattendance_byemployee_nic> search_Attendance_by_Employeeid_AllDetails = Attendance_Contorller.search_Attendance_by_EmployeeNIC_AllDetails(ComboEmployeeNic1.getSelectedItem().toString(),Texdate.getText());
                for(getattendance_byemployee_nic attendance:search_Attendance_by_Employeeid_AllDetails){
                    if (attendance.getDate().equals(Texdate.getText())) {
                        texAttend.setText(attendance.getAttend());
                        TextArrivaltime1.setText(String.valueOf(attendance.getArrival_time()));
                    }
                }
            } else {
                //Toolkit.getDefaultToolkit().beep();
                //JOptionPane.showMessageDialog(this, "No Enployee In System !!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
