/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.Attendance;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.smsc.controller1.Attendance_Contorller;
import com.smsc.controller1.Empolyee_Controller;
import com.smsc.db.DBController;
import com.smsc.model.Attendance;
import com.smsc.model.Employee;
import com.smsc.other.Validation;
import java.util.Arrays;

/**
 *
 * @author linux
 */
public class Search_Attendance extends javax.swing.JFrame {
    private String ATID;
    private String EID;
    private Connection connection;
    private String employeecount;
    int xmouse;
    int ymouse;
    /**
     * Creates new form Search_Attendance
     */
    public Search_Attendance() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        try {
            connection=DBController.createConnection().getConnection();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formatedDate = dateFormat.format(date);
        labdate.setText(formatedDate);
    }
    /*public void print(){
        try {
            JasperReport compileReport = JasperCompileManager.compileReport(getClass().getResourceAsStream("AttendanceReport.jrxml"));
            JasperPrint fillReport=JasperFillManager.fillReport(compileReport, null,connection);
            JasperViewer.viewReport(fillReport,false);
        } catch (JRException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btexit = new javax.swing.JButton();
        btmini = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablView = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Combocelectemployee = new javax.swing.JComboBox();
        btSearcha = new javax.swing.JButton();
        texNic = new javax.swing.JTextField();
        btGetAttendanceReport = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btRemoveAttendance = new javax.swing.JButton();
        btUpdateAttendance = new javax.swing.JButton();
        texDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        texEmployeename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Labelattend = new javax.swing.JLabel();
        texAttend = new javax.swing.JTextField();
        TextArrivaltime = new javax.swing.JTextField();
        Labelarrivaltime = new javax.swing.JLabel();
        Labelleavetime = new javax.swing.JLabel();
        TextLeavetime = new javax.swing.JTextField();
        TextOtamount = new javax.swing.JTextField();
        Labelotamount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        texDatetype = new javax.swing.JTextField();
        btreload = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labdate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Attendance");
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btexit.setText("X");
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btexitMouseClicked(evt);
            }
        });
        jPanel1.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, -1));

        btmini.setText("_");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        jPanel1.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, -1, -1));

        tablView.setBackground(new java.awt.Color(102, 153, 255));
        tablView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Date", "Date Type", "Attend", "Arrival Time", "Leave Time", "Ot Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablViewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablView);
        if (tablView.getColumnModel().getColumnCount() > 0) {
            tablView.getColumnModel().getColumn(0).setResizable(false);
            tablView.getColumnModel().getColumn(1).setResizable(false);
            tablView.getColumnModel().getColumn(2).setResizable(false);
            tablView.getColumnModel().getColumn(3).setResizable(false);
            tablView.getColumnModel().getColumn(4).setResizable(false);
            tablView.getColumnModel().getColumn(5).setResizable(false);
            tablView.getColumnModel().getColumn(6).setResizable(false);
        }

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 460, 260));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee Nic No :  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Search For  : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));

        Combocelectemployee.setBackground(new java.awt.Color(255, 255, 255));
        Combocelectemployee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Combocelectemployee.setForeground(new java.awt.Color(0, 0, 102));
        Combocelectemployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "One Employee", "All Employees" }));
        Combocelectemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombocelectemployeeActionPerformed(evt);
            }
        });
        jPanel1.add(Combocelectemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 30));

        btSearcha.setBackground(new java.awt.Color(102, 102, 102));
        btSearcha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btSearcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/search.png"))); // NOI18N
        btSearcha.setText("Search");
        btSearcha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchaActionPerformed(evt);
            }
        });
        jPanel1.add(btSearcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 40));

        texNic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texNic.setForeground(new java.awt.Color(0, 0, 153));
        texNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texNicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texNicKeyReleased(evt);
            }
        });
        jPanel1.add(texNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 40));

        btGetAttendanceReport.setBackground(new java.awt.Color(102, 102, 102));
        btGetAttendanceReport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btGetAttendanceReport.setText("Get Report");
        btGetAttendanceReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGetAttendanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetAttendanceReportActionPerformed(evt);
            }
        });
        jPanel1.add(btGetAttendanceReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 120, 40));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRemoveAttendance.setBackground(new java.awt.Color(102, 102, 102));
        btRemoveAttendance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRemoveAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/delete.png"))); // NOI18N
        btRemoveAttendance.setText("Remove Attendance");
        btRemoveAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRemoveAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveAttendanceActionPerformed(evt);
            }
        });
        jPanel5.add(btRemoveAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 180, 40));

        btUpdateAttendance.setBackground(new java.awt.Color(102, 102, 102));
        btUpdateAttendance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btUpdateAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/arrow_up.png"))); // NOI18N
        btUpdateAttendance.setText("Update Attendance");
        btUpdateAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUpdateAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateAttendanceActionPerformed(evt);
            }
        });
        jPanel5.add(btUpdateAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 170, 40));

        texDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texDate.setForeground(new java.awt.Color(0, 0, 102));
        texDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texDateKeyReleased(evt);
            }
        });
        jPanel5.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date  : ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 30));

        texEmployeename.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texEmployeename.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(texEmployeename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Employee Name  : ");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 30));

        Labelattend.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelattend.setForeground(new java.awt.Color(0, 0, 102));
        Labelattend.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelattend.setText("Attend  : ");
        jPanel5.add(Labelattend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        texAttend.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texAttend.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(texAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 180, 30));

        TextArrivaltime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TextArrivaltime.setForeground(new java.awt.Color(0, 0, 102));
        TextArrivaltime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextArrivaltime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextArrivaltimeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextArrivaltimeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextArrivaltimeKeyTyped(evt);
            }
        });
        jPanel5.add(TextArrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 180, 30));

        Labelarrivaltime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelarrivaltime.setForeground(new java.awt.Color(0, 0, 102));
        Labelarrivaltime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelarrivaltime.setText("Arrival Time  : ");
        jPanel5.add(Labelarrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        Labelleavetime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelleavetime.setForeground(new java.awt.Color(0, 0, 102));
        Labelleavetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelleavetime.setText("Leave Time  : ");
        jPanel5.add(Labelleavetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, -1));

        TextLeavetime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TextLeavetime.setForeground(new java.awt.Color(0, 0, 102));
        TextLeavetime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextLeavetime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextLeavetimeKeyReleased(evt);
            }
        });
        jPanel5.add(TextLeavetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 180, 30));

        TextOtamount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TextOtamount.setForeground(new java.awt.Color(0, 0, 102));
        TextOtamount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(TextOtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 230, 30));

        Labelotamount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Labelotamount.setForeground(new java.awt.Color(0, 0, 102));
        Labelotamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelotamount.setText("Ot Amount  : ");
        jPanel5.add(Labelotamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Date Type  : ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));
        jPanel5.add(texDatetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 640, 260));

        btreload.setBackground(new java.awt.Color(102, 102, 102));
        btreload.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btreload.setText("Reload To Past");
        btreload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreloadActionPerformed(evt);
            }
        });
        jPanel1.add(btreload, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 150, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SMSC Payroll");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Employee Attendance");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, 40));

        labdate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(labdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 210, 40));

        jLabel8.setBackground(new java.awt.Color(0, 102, 153));
        jLabel8.setOpaque(true);
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1117, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 433));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchaActionPerformed
        searchAttendance();
    }//GEN-LAST:event_btSearchaActionPerformed

    private void tablViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablViewMouseClicked
        settextofill();
    }//GEN-LAST:event_tablViewMouseClicked

    private void TextArrivaltimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextArrivaltimeKeyPressed
        
    }//GEN-LAST:event_TextArrivaltimeKeyPressed

    private void texNicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texNicKeyPressed
        
    }//GEN-LAST:event_texNicKeyPressed

    private void texNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texNicKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(texNic);
        }
    }//GEN-LAST:event_texNicKeyReleased

    private void TextArrivaltimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextArrivaltimeKeyReleased
    if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
        Validation.validateTime(TextArrivaltime);
    }
    }//GEN-LAST:event_TextArrivaltimeKeyReleased

    private void TextLeavetimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextLeavetimeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
        Validation.validateTime(TextLeavetime);
    } 
    }//GEN-LAST:event_TextLeavetimeKeyReleased

    private void texDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texDateKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateDate(texDate);
        }
    }//GEN-LAST:event_texDateKeyReleased

    private void btUpdateAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateAttendanceActionPerformed
        updateAttendance();
    }//GEN-LAST:event_btUpdateAttendanceActionPerformed

    private void TextArrivaltimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextArrivaltimeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextArrivaltimeKeyTyped

    private void btGetAttendanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetAttendanceReportActionPerformed

    }//GEN-LAST:event_btGetAttendanceReportActionPerformed

    private void btRemoveAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveAttendanceActionPerformed
        removeAttendance();
    }//GEN-LAST:event_btRemoveAttendanceActionPerformed

    private void btreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreloadActionPerformed
        try {
            loadallAttendance();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btreloadActionPerformed

    private void CombocelectemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombocelectemployeeActionPerformed
        employeecount=String.valueOf(Combocelectemployee.getSelectedItem());
    }//GEN-LAST:event_CombocelectemployeeActionPerformed

    private void btexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseClicked
    this.dispose();
    }//GEN-LAST:event_btexitMouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        this.setState(Search_Attendance.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_jLabel8MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Search_Attendance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combocelectemployee;
    private javax.swing.JLabel Labelarrivaltime;
    private javax.swing.JLabel Labelattend;
    private javax.swing.JLabel Labelleavetime;
    private javax.swing.JLabel Labelotamount;
    private javax.swing.JTextField TextArrivaltime;
    private javax.swing.JTextField TextLeavetime;
    private javax.swing.JTextField TextOtamount;
    private javax.swing.JButton btGetAttendanceReport;
    private javax.swing.JButton btRemoveAttendance;
    private javax.swing.JButton btSearcha;
    private javax.swing.JButton btUpdateAttendance;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btmini;
    private javax.swing.JButton btreload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labdate;
    private javax.swing.JTable tablView;
    private javax.swing.JTextField texAttend;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texDatetype;
    private javax.swing.JTextField texEmployeename;
    private javax.swing.JTextField texNic;
    // End of variables declaration//GEN-END:variables

    private void getATID() {
        try {
            ArrayList<Attendance> search_Attendance_by_Employeeid = Attendance_Contorller.search_Attendance_by_Attendanceemployeeid(EID);
            for(Attendance attendance : search_Attendance_by_Employeeid){
                if (attendance.getDate().equals(texDate.getText())) {
                    ATID=attendance.getAtid();
                } else {
                    ATID=null;
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int updateAttendance(String EID, String date, String datetype, String attend, String arrivaltime, String leavetime, String otbonus, String ATID) throws ClassNotFoundException, SQLException {
        Attendance attendance=new Attendance(ATID, EID, date, datetype, attend, arrivaltime, leavetime, Double.parseDouble(otbonus));
        int update_Attendance_AllDetails = Attendance_Contorller.update_Attendance_AllDetails(attendance);
        if (update_Attendance_AllDetails > 0) {
            return 1;
        } else {
            return 0;
        }
    }

    private int removeattendance(String ATID) throws ClassNotFoundException, SQLException {
        int delete_Attedance = Attendance_Contorller.delete_Attedance(ATID);
        if (delete_Attedance > 0) {
            return 1;
        } else {
            return 0;
        }
    }

    private void loaddataToTable() throws ClassNotFoundException, SQLException {
        Empolyee_Controller empolyee_Controller = new Empolyee_Controller();
                Employee Search_Employee_by_Nic = empolyee_Controller.Search_Employee_by_Nic(texNic.getText());
                if(Search_Employee_by_Nic != null){
                    ArrayList<Attendance> search_Attendance_by_Employeeid = Attendance_Contorller.search_Attendance_by_Attendanceemployeeid(Search_Employee_by_Nic.getEid());
                    DefaultTableModel dtm=(DefaultTableModel) tablView.getModel();
                    dtm.setRowCount(0);
                    for(Attendance attendance: search_Attendance_by_Employeeid){
                        Object[]row={Search_Employee_by_Nic.getLastname(),attendance.getDate(),attendance.getDate_type(),attendance.getAttend(),attendance.getArrival_Time(),attendance.getLeave_Time(),attendance.getOt_Bonus()};
                        dtm.addRow(row);
                        EID=Search_Employee_by_Nic.getEid();
                    }
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this,"No Employee In System\n"+texNic.getText());
                }
    }

    private void loadmonthattendance(String year) throws ClassNotFoundException, SQLException {
        ArrayList<Attendance> monthAttendance = new Attendance_Contorller().getMonthAttendance(year);
        DefaultTableModel dtm=(DefaultTableModel) tablView.getModel();
        dtm.setRowCount(0);
        for(Attendance attendance: monthAttendance){
            Employee Search_Employee_by_id = new Empolyee_Controller().Search_Employee_by_id(attendance.getEid());
            Object[]row={Search_Employee_by_id.getLastname(),attendance.getDate(),attendance.getDate_type(),attendance.getAttend(),attendance.getArrival_Time(),attendance.getLeave_Time(),attendance.getOt_Bonus()};
            dtm.addRow(row);
        }
    }

    private void loadallAttendance() throws ClassNotFoundException, SQLException {
        ArrayList<Attendance> allAttendance = Attendance_Contorller.getallAttendance();
        DefaultTableModel dtm=(DefaultTableModel) tablView.getModel();
        dtm.setRowCount(0);
        for(Attendance attendance: allAttendance){
            Employee Search_Employee_by_id = new Empolyee_Controller().Search_Employee_by_id(attendance.getEid());
            Object[]row={Search_Employee_by_id.getLastname(),attendance.getDate(),attendance.getDate_type(),attendance.getAttend(),attendance.getArrival_Time(),attendance.getLeave_Time(),attendance.getOt_Bonus()};
            dtm.addRow(row);
        }
    }

    private void searchAttendance() {
        String year = Arrays.toString(labdate.getText().split("-",0));
        String month = Arrays.toString(labdate.getText().split("-",1));
        String date=year+"-"+month+"-";
        if (employeecount.equals("One Employee")) {
            try {
                loaddataToTable();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                loadmonthattendance(date);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void settextofill() {
        int selectedRow = tablView.getSelectedRow();
        String Employeename=tablView.getValueAt(selectedRow, 0).toString();
        String Date=tablView.getValueAt(selectedRow, 1).toString();
        String DateType=tablView.getValueAt(selectedRow, 2).toString();
        String Attend=tablView.getValueAt(selectedRow, 3).toString();
        String Arrivaltime=tablView.getValueAt(selectedRow, 4).toString();
        String Leavetime=tablView.getValueAt(selectedRow, 5).toString();
        String ot = tablView.getValueAt(selectedRow, 6).toString();
        texEmployeename.setText(Employeename);
        texAttend.setText(Attend);
        TextArrivaltime.setText(Arrivaltime);
        TextLeavetime.setText(Leavetime);
        TextOtamount.setText(ot);
        texDate.setText(Date);
        texDatetype.setText(DateType);
        getATID();
    }

    private void updateAttendance() {
        try {
            int updateAttendance = updateAttendance(EID,texDate.getText(),texDatetype.getText(),texAttend.getText(),TextArrivaltime.getText(),TextLeavetime.getText(),TextOtamount.getText(),ATID);
            if (updateAttendance ==1) {
                JOptionPane.showMessageDialog(this, "Attendance Update Success !!!");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Attendance Update Fail !!!\n Check your Text and try again !!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeAttendance() {
        try {
            int removeattendance = removeattendance(ATID);
            if (removeattendance ==1) {
                JOptionPane.showMessageDialog(this, "Attendance Remove Success !!!");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Attendance Remove Fail !!! \n check you did work and try agaiv !!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
