/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.main.other;

import java.util.StringTokenizer;

/**
 *
 * @author linux
 */
public class cal extends javax.swing.JFrame {
        private Double number1;
	private Double number2;
	private Double number3;	
        private char op;
        private int number;
        private int number12;
        private int number23;
        private boolean ison=false;
    /**
     * Creates new form cal
     */
    public cal() {
        initComponents();
        setLocationRelativeTo(null);
        displayText.setEditable(false);
        bt0.setEnabled(false);
        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
        bt5.setEnabled(false);
        bt6.setEnabled(false);
        bt7.setEnabled(false);
        bt8.setEnabled(false);
        bt9.setEnabled(false);
        btDiv.setEnabled(false);
        btMul.setEnabled(false);
        btSub.setEnabled(false);
        btAdd.setEnabled(false);
        btEquals.setEnabled(false);
        btDec.setEnabled(false);
        ClearButton.setEnabled(false);
       displayText.setHorizontalAlignment(displayText.RIGHT);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayText = new javax.swing.JTextField();
        bt7 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btMul = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btSub = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btEquals = new javax.swing.JButton();
        btDec = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        l60 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l50 = new javax.swing.JLabel();
        l0 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayText.setBackground(new java.awt.Color(204, 204, 204));
        displayText.setFont(new java.awt.Font("David", 0, 24)); // NOI18N
        displayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTextActionPerformed(evt);
            }
        });
        jPanel1.add(displayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 270, 30));

        bt7.setBackground(new java.awt.Color(51, 51, 51));
        bt7.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("7");
        bt7.setBorderPainted(false);
        bt7.setContentAreaFilled(false);
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 50));

        bt9.setBackground(new java.awt.Color(51, 51, 51));
        bt9.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("9");
        bt9.setBorderPainted(false);
        bt9.setContentAreaFilled(false);
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 60, 50));

        btDiv.setBackground(new java.awt.Color(0, 102, 153));
        btDiv.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btDiv.setForeground(new java.awt.Color(255, 255, 255));
        btDiv.setText("/");
        btDiv.setBorderPainted(false);
        btDiv.setContentAreaFilled(false);
        btDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivActionPerformed(evt);
            }
        });
        jPanel1.add(btDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, 50));

        bt8.setBackground(new java.awt.Color(51, 51, 51));
        bt8.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("8");
        bt8.setBorderPainted(false);
        bt8.setContentAreaFilled(false);
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 50));

        bt5.setBackground(new java.awt.Color(51, 51, 51));
        bt5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("5");
        bt5.setBorderPainted(false);
        bt5.setContentAreaFilled(false);
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 50));

        bt4.setBackground(new java.awt.Color(51, 51, 51));
        bt4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("4");
        bt4.setBorderPainted(false);
        bt4.setContentAreaFilled(false);
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 50));

        bt6.setBackground(new java.awt.Color(51, 51, 51));
        bt6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("6");
        bt6.setBorderPainted(false);
        bt6.setContentAreaFilled(false);
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 60, 50));

        btMul.setBackground(new java.awt.Color(0, 102, 153));
        btMul.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btMul.setForeground(new java.awt.Color(255, 255, 255));
        btMul.setText("*");
        btMul.setBorderPainted(false);
        btMul.setContentAreaFilled(false);
        btMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMulActionPerformed(evt);
            }
        });
        jPanel1.add(btMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 60, 50));

        bt2.setBackground(new java.awt.Color(51, 51, 51));
        bt2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("2");
        bt2.setBorderPainted(false);
        bt2.setContentAreaFilled(false);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 50));

        bt1.setBackground(new java.awt.Color(51, 51, 51));
        bt1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("1");
        bt1.setBorderPainted(false);
        bt1.setContentAreaFilled(false);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 50));

        bt3.setBackground(new java.awt.Color(51, 51, 51));
        bt3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("3");
        bt3.setBorderPainted(false);
        bt3.setContentAreaFilled(false);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 50));

        btSub.setBackground(new java.awt.Color(0, 102, 153));
        btSub.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btSub.setForeground(new java.awt.Color(255, 255, 255));
        btSub.setText("-");
        btSub.setBorderPainted(false);
        btSub.setContentAreaFilled(false);
        btSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubActionPerformed(evt);
            }
        });
        jPanel1.add(btSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 50));

        bt0.setBackground(new java.awt.Color(51, 51, 51));
        bt0.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bt0.setForeground(new java.awt.Color(255, 255, 255));
        bt0.setText("0");
        bt0.setBorderPainted(false);
        bt0.setContentAreaFilled(false);
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 50));

        btEquals.setBackground(new java.awt.Color(0, 153, 0));
        btEquals.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btEquals.setForeground(new java.awt.Color(255, 255, 255));
        btEquals.setText("=");
        btEquals.setBorderPainted(false);
        btEquals.setContentAreaFilled(false);
        btEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEqualsActionPerformed(evt);
            }
        });
        jPanel1.add(btEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 60, 50));

        btDec.setBackground(new java.awt.Color(51, 51, 51));
        btDec.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btDec.setForeground(new java.awt.Color(255, 255, 255));
        btDec.setText(".");
        btDec.setBorderPainted(false);
        btDec.setContentAreaFilled(false);
        btDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecActionPerformed(evt);
            }
        });
        jPanel1.add(btDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, 50));

        btAdd.setBackground(new java.awt.Color(0, 102, 153));
        btAdd.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setText("+");
        btAdd.setBorderPainted(false);
        btAdd.setContentAreaFilled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel1.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 60, 50));

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 30));

        pButton.setText("On/Off");
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 30));

        l60.setBackground(new java.awt.Color(0, 102, 153));
        l60.setOpaque(true);
        jPanel1.add(l60, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 60, 50));

        l40.setBackground(new java.awt.Color(0, 102, 51));
        l40.setOpaque(true);
        jPanel1.add(l40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 60, 50));

        l50.setBackground(new java.awt.Color(51, 51, 51));
        l50.setOpaque(true);
        jPanel1.add(l50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, 50));

        l0.setBackground(new java.awt.Color(51, 51, 51));
        l0.setOpaque(true);
        jPanel1.add(l0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 50));

        l1.setBackground(new java.awt.Color(51, 51, 51));
        l1.setOpaque(true);
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 50));

        l4.setBackground(new java.awt.Color(51, 51, 51));
        l4.setOpaque(true);
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 50));

        l2.setBackground(new java.awt.Color(51, 51, 51));
        l2.setOpaque(true);
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 50));

        l3.setBackground(new java.awt.Color(51, 51, 51));
        l3.setOpaque(true);
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 50));

        l30.setBackground(new java.awt.Color(0, 102, 153));
        l30.setOpaque(true);
        jPanel1.add(l30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 50));

        l5.setBackground(new java.awt.Color(51, 51, 51));
        l5.setOpaque(true);
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 50));

        l6.setBackground(new java.awt.Color(51, 51, 51));
        l6.setOpaque(true);
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 60, 50));

        l20.setBackground(new java.awt.Color(0, 102, 153));
        l20.setOpaque(true);
        jPanel1.add(l20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 60, 50));

        l10.setBackground(new java.awt.Color(0, 102, 153));
        l10.setOpaque(true);
        jPanel1.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, 50));

        l9.setBackground(new java.awt.Color(51, 51, 51));
        l9.setOpaque(true);
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 60, 50));

        l8.setBackground(new java.awt.Color(51, 51, 51));
        l8.setOpaque(true);
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 50));

        l7.setBackground(new java.awt.Color(51, 51, 51));
        l7.setOpaque(true);
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 50));

        jLabel1.setText("Plese povr");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTextActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_displayTextActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
 displayText.setText(displayText.getText()+bt1.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
    displayText.setText(displayText.getText()+bt0.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
 displayText.setText(displayText.getText()+bt2.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
 displayText.setText(displayText.getText()+bt3.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
 displayText.setText(displayText.getText()+bt4.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
 displayText.setText(displayText.getText()+bt5.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
 displayText.setText(displayText.getText()+bt6.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
 displayText.setText(displayText.getText()+bt7.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
 displayText.setText(displayText.getText()+bt8.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
 displayText.setText(displayText.getText()+bt9.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_bt9ActionPerformed

    private void btDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivActionPerformed
        StringTokenizer st=new StringTokenizer(displayText.getText(),".");
        if (st.hasMoreTokens()) {
            number1 = Double.parseDouble(displayText.getText());            
            displayText.setText(" ");
            op = '/';
        } else {
            number=Integer.parseInt(displayText.getText());
            displayText.setText(" ");
            op='/';
        }
    }//GEN-LAST:event_btDivActionPerformed

    private void btMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMulActionPerformed
        StringTokenizer st=new StringTokenizer(displayText.getText(),".");
        if (st.hasMoreTokens()) {
            number1 = Double.parseDouble(displayText.getText());            
            displayText.setText(" ");
            op = '*';
        } else {
            number=Integer.parseInt(displayText.getText());
            displayText.setText(" ");
            op='*';
        }
    }//GEN-LAST:event_btMulActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
	StringTokenizer st=new StringTokenizer(displayText.getText(),".");
        if (st.hasMoreTokens()) {
            number1 = Double.parseDouble(displayText.getText());            
            displayText.setText(" ");
            op = '+';
        } else {
            number=Integer.parseInt(displayText.getText());
            displayText.setText(" ");
            op='+';
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecActionPerformed
    displayText.setText(displayText.getText()+btDec.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btDecActionPerformed

    private void btEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEqualsActionPerformed
            String text=displayText.getText();
            StringTokenizer st=new StringTokenizer(text,".");
            //String s=st.nextToken();
        if (st.hasMoreTokens()) {
            number2 = Double.parseDouble(text);
            switch (op) {
                case '+':
                    number3 = number1 + number2;
                    break;
                case '-':
                    number3 = number1 - number2;
                    break;
                case '*':
                    number3 = number1 * number2;
                    break;
                case '/':
                    number3 = number1 / number2;
                    break;
            }
            displayText.setText(""+number3);
        } else {
            number12=Integer.parseInt(text);
            switch (op) {
                case '+':
                    number23 = number + number12;
                    break;
                case '-':
                    number23 = number - number12;
                    break;
                case '*':
                    number23 = number * number12;
                    break;
                case '/':
                    number23 = number / number12;
                    break;
            }
            displayText.setText(""+number23);
        }
            
    }//GEN-LAST:event_btEqualsActionPerformed

    private void btSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubActionPerformed
	StringTokenizer st=new StringTokenizer(displayText.getText(),".");
        if (st.hasMoreTokens()) {
            number3 = Double.parseDouble(displayText.getText());            
            displayText.setText(" ");
            op = '-';
        } else {
            number=Integer.parseInt(displayText.getText());
            displayText.setText(" ");
            op='-';
        }
    }//GEN-LAST:event_btSubActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        if (ison==false) {
            displayText.setEditable(true);
            bt0.setEnabled(true);
            bt1.setEnabled(true);
            bt2.setEnabled(true);
            bt3.setEnabled(true);
            bt4.setEnabled(true);
            bt5.setEnabled(true);
            bt6.setEnabled(true);
            bt7.setEnabled(true);
            bt8.setEnabled(true);
            bt9.setEnabled(true);
            btDiv.setEnabled(true);
            btMul.setEnabled(true);
            btSub.setEnabled(true);
            btAdd.setEnabled(true);
            btEquals.setEnabled(true);
            btDec.setEnabled(true);
            ClearButton.setEnabled(true);
            ison=true;
        } else {
            displayText.setEditable(false);
            bt0.setEnabled(false);
            bt1.setEnabled(false);
            bt2.setEnabled(false);
            bt3.setEnabled(false);
            bt4.setEnabled(false);
            bt5.setEnabled(false);
            bt6.setEnabled(false);
            bt7.setEnabled(false);
            bt8.setEnabled(false);
            bt9.setEnabled(false);
            btDiv.setEnabled(false);
            btMul.setEnabled(false);
            btSub.setEnabled(false);
            btAdd.setEnabled(false);
            btEquals.setEnabled(false);
            btDec.setEnabled(false);
            ClearButton.setEnabled(false);
            ison=false;
        }
    }//GEN-LAST:event_pButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        displayText.setText(" ");
        number=0;
        number1=0.0;
        number12=0;
        number2=0.0;
        number23=0;
        number3=0.0;
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDec;
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btEquals;
    private javax.swing.JButton btMul;
    private javax.swing.JButton btSub;
    private javax.swing.JTextField displayText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l0;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l40;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l50;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l60;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JButton pButton;
    // End of variables declaration//GEN-END:variables
}
