/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.unions;

import com.smsc.controller1.Union_Controller;
import com.smsc.model.Unions;
import com.smsc.other.IdGenerator;
import com.smsc.other.Validation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smsc
 */
public class Input_New_Union extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    int selectedRow;
    DefaultTableModel tableModel;
    /**
     * Creates new form Input_New_Union
     */
    public Input_New_Union() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        getID();
        texName.requestFocus();
        btDone.setEnabled(false);
        btRemove.setEnabled(false);
        btinput.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texID = new javax.swing.JTextField();
        texOpenDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        texFee = new javax.swing.JTextField();
        texName = new javax.swing.JTextField();
        btinput = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        texDate = new javax.swing.JTextField();
        btRemove = new javax.swing.JButton();
        btDone = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUnions = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texReno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Union Id  :  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name  :  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));

        texID.setEditable(false);
        texID.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.add(texID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 70, 30));

        texOpenDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texOpenDateActionPerformed(evt);
            }
        });
        texOpenDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texOpenDateKeyReleased(evt);
            }
        });
        jPanel1.add(texOpenDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Open Date  :  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Membership Fee  :  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        texFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFeeActionPerformed(evt);
            }
        });
        texFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texFeeKeyReleased(evt);
            }
        });
        jPanel1.add(texFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 30));

        texName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNameActionPerformed(evt);
            }
        });
        jPanel1.add(texName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 350, 30));

        btinput.setBackground(new java.awt.Color(102, 102, 102));
        btinput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btinput.setText("Input ");
        btinput.setBorderPainted(false);
        btinput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinputActionPerformed(evt);
            }
        });
        jPanel1.add(btinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 700, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Date  :  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        texDate.setEditable(false);
        texDate.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 170, -1));

        btRemove.setBackground(new java.awt.Color(102, 102, 102));
        btRemove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btRemove.setText("Remove ..");
        btRemove.setBorderPainted(false);
        btRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        btDone.setBackground(new java.awt.Color(102, 102, 102));
        btDone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btDone.setText("Input Done");
        btDone.setBorderPainted(false);
        btDone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        tabUnions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Uid", "Name", "Open Date", "Fee", "Register No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUnions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUnionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabUnions);
        if (tabUnions.getColumnModel().getColumnCount() > 0) {
            tabUnions.getColumnModel().getColumn(0).setResizable(false);
            tabUnions.getColumnModel().getColumn(1).setResizable(false);
            tabUnions.getColumnModel().getColumn(2).setResizable(false);
            tabUnions.getColumnModel().getColumn(3).setResizable(false);
            tabUnions.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 544, 208));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setOpaque(true);
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 710, 26));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 260));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Input New Union");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 690, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Register No  :  ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, -1));

        texReno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRenoActionPerformed(evt);
            }
        });
        jPanel1.add(texReno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 712, 566));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
        inputToDatabase();
    }//GEN-LAST:event_btDoneActionPerformed

    private void texFeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texFeeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE || evt.getKeyCode() != KeyEvent.VK_PROPS) {
            Validation.validatenumber(texFee);
        }
    }//GEN-LAST:event_texFeeKeyReleased

    private void texOpenDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texOpenDateKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateDate(texOpenDate);
        }
    }//GEN-LAST:event_texOpenDateKeyReleased

    private void btinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinputActionPerformed
        inputToTable();
    }//GEN-LAST:event_btinputActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Input_New_Union.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        ifremove();
    }//GEN-LAST:event_btRemoveActionPerformed

    private void tabUnionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUnionsMouseClicked
        getValue();
    }//GEN-LAST:event_tabUnionsMouseClicked

    private void texNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNameActionPerformed
        texOpenDate.requestFocus();
    }//GEN-LAST:event_texNameActionPerformed

    private void texOpenDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texOpenDateActionPerformed
        texFee.requestFocus();
    }//GEN-LAST:event_texOpenDateActionPerformed

    private void texFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFeeActionPerformed
        texReno.requestFocus();
    }//GEN-LAST:event_texFeeActionPerformed

    private void texRenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRenoActionPerformed
        btinput.setEnabled(true);
    }//GEN-LAST:event_texRenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_New_Union.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_New_Union.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_New_Union.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_New_Union.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_New_Union().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDone;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btinput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabUnions;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texFee;
    private javax.swing.JTextField texID;
    private javax.swing.JTextField texName;
    private javax.swing.JTextField texOpenDate;
    private javax.swing.JTextField texReno;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date date =new Date();
        SimpleDateFormat dateFormat=new SimpleDateFormat("YYYY-MM-DD");
        String format = dateFormat.format(date);
        texDate.setText(format);
    }

    private void getID() {
        try {
            String newId = IdGenerator.getNewId("Unions", "Uid", "U");
            texID.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Input_New_Union.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void inputToTable() {
        String id = texID.getText();
        double fee = Double.parseDouble(texFee.getText());
        String name = texName.getText();
        String opDate = texOpenDate.getText();
        String reno = texReno.getText();
        tableModel=(DefaultTableModel) tabUnions.getModel();
        Object[] row={id,name,opDate,fee,reno};
        tableModel.addRow(row);
        getID();
        btRemove.setEnabled(true);
        btDone.setEnabled(true);
    }

    private void ifremove() {
        if (selectedRow > -1) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are You want Remove this !!!");
            if (showConfirmDialog == JOptionPane.YES_OPTION) {
                removr();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to remove !!!");
        }
    }

    private void getValue() {
        selectedRow = tabUnions.getSelectedRow();
    }

    private void removr() {
        tableModel.removeRow(selectedRow);
        selectedRow=-1;
    }

    private void inputToDatabase() {
        int count=0;
        int rowCount = tabUnions.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String uid = tabUnions.getValueAt(i, 0).toString();
            String name = tabUnions.getValueAt(i, 1).toString();
            String opdate = tabUnions.getValueAt(i, 2).toString();
            double fee = Double.parseDouble(tabUnions.getValueAt(i, 3).toString());
            String reno = tabUnions.getValueAt(i, 4).toString();
            
            Unions unions=new Unions(uid, name, opdate, fee, reno);
            try {
                int inputUnions = new Union_Controller().inputUnions(unions);
                if (inputUnions > 0) {
                    count++;
                }
            } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Input_New_Union.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (count==rowCount) {
            JOptionPane.showMessageDialog(this, "Unions Input Success !!!");
            tableModel.removeRow(rowCount);
        } else {
            JOptionPane.showMessageDialog(this, "Unoins Input Fail !! \n Try again !!!");
        }
    }
}
