/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.job_role;

import com.smsc.controller1.Company_Details_Controller;
import com.smsc.db.DBController;
import com.smsc.model.Company_Details;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author smsc
 */
public class getReports extends javax.swing.JFrame {
 int xmouse;
 int ymouse;
 Connection connection;
 private String coName=null;
 private String coAddress=null;
 private String coTele=null;
 private String coEmail=null;
 private String coFax=null;
 
    /**
     * Creates new form getReports
     */
    public getReports() {
        initComponents();
        setLocationRelativeTo(null);
        getCompanyDetails();
        try {
            connection=DBController.createConnection().getConnection();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(getReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void print(String parth) throws JRException {
        HashMap<String,Object> map=new HashMap<>();
        JasperReport compileReport = JasperCompileManager.compileReport(getClass().getResourceAsStream(parth));
        map.put("name", coName);
        map.put("address", coAddress);
        map.put("tele", coTele);
        map.put("fax", coFax);
        map.put("email", coEmail);
        JasperPrint fillReport = JasperFillManager.fillReport(compileReport, map, connection);
        JasperViewer.viewReport(fillReport, false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labAllJobRolesCustomDetails = new javax.swing.JLabel();
        btViewReportone = new javax.swing.JButton();
        labOneJobRoleDetails = new javax.swing.JLabel();
        checkBoxjobroleName = new javax.swing.JCheckBox();
        CheckBoxnoofEmployees = new javax.swing.JCheckBox();
        labAllJobRoleDetails = new javax.swing.JLabel();
        btViewReport = new javax.swing.JButton();
        btViewReportcustom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labAllJobRolesCustomDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labAllJobRolesCustomDetails.setForeground(new java.awt.Color(0, 0, 102));
        labAllJobRolesCustomDetails.setText("All Job Roles In Custom Details  : ");
        jPanel1.add(labAllJobRolesCustomDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btViewReportone.setBackground(new java.awt.Color(102, 102, 102));
        btViewReportone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btViewReportone.setText("View Report");
        btViewReportone.setBorderPainted(false);
        btViewReportone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btViewReportone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 130, 30));

        labOneJobRoleDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labOneJobRoleDetails.setForeground(new java.awt.Color(0, 0, 102));
        labOneJobRoleDetails.setText("One Job Role In All Details  : ");
        jPanel1.add(labOneJobRoleDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 300, -1));

        buttonGroup1.add(checkBoxjobroleName);
        checkBoxjobroleName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkBoxjobroleName.setForeground(new java.awt.Color(0, 0, 102));
        checkBoxjobroleName.setText("Job Role Name and Pension Age");
        checkBoxjobroleName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBoxjobroleName.setOpaque(false);
        jPanel1.add(checkBoxjobroleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        buttonGroup1.add(CheckBoxnoofEmployees);
        CheckBoxnoofEmployees.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CheckBoxnoofEmployees.setForeground(new java.awt.Color(0, 0, 102));
        CheckBoxnoofEmployees.setText("No of Employees in each job role");
        CheckBoxnoofEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBoxnoofEmployees.setOpaque(false);
        jPanel1.add(CheckBoxnoofEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        labAllJobRoleDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labAllJobRoleDetails.setForeground(new java.awt.Color(0, 0, 102));
        labAllJobRoleDetails.setText("All Job Roles In All Details  : ");
        jPanel1.add(labAllJobRoleDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, -1));

        btViewReport.setBackground(new java.awt.Color(102, 102, 102));
        btViewReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btViewReport.setText("View Report");
        btViewReport.setBorderPainted(false);
        btViewReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewReportActionPerformed(evt);
            }
        });
        jPanel1.add(btViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 130, 30));

        btViewReportcustom.setBackground(new java.awt.Color(102, 102, 102));
        btViewReportcustom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btViewReportcustom.setText("View Report");
        btViewReportcustom.setBorderPainted(false);
        btViewReportcustom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btViewReportcustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 130, 30));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 660, 26));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Get Job Role Reports");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 630, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 210, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 444));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(getReports.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewReportActionPerformed
        try {
            print("PrintAlljobRole.jrxml");
        } catch (JRException ex) {
            Logger.getLogger(getReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btViewReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxnoofEmployees;
    private javax.swing.JButton btViewReport;
    private javax.swing.JButton btViewReportcustom;
    private javax.swing.JButton btViewReportone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxjobroleName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAllJobRoleDetails;
    private javax.swing.JLabel labAllJobRolesCustomDetails;
    private javax.swing.JLabel labOneJobRoleDetails;
    // End of variables declaration//GEN-END:variables


    private void getCompanyDetails() {
        try {
            Company_Details searchCompany_Details = new Company_Details_Controller().searchCompany_Details();
            coName=searchCompany_Details.getCompany_Name();
            coAddress=searchCompany_Details.getCompany_Address();
            coEmail=searchCompany_Details.getE_Mail();
            coTele=searchCompany_Details.getTelephone();
            coFax=searchCompany_Details.getFax();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(getReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
