/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.job_role;

import java.awt.Color;

/**
 *
 * @author smsc
 */
public class Manage_Job_Role_info extends javax.swing.JPanel {
    private input_jobrole inputnew=null;
    private search_jobrole search=null;
    private getReports view=null;
    /**
     * Creates new form Manage_Job_Role_info
     */
    public Manage_Job_Role_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btinputnew = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btinputnew.setBackground(new java.awt.Color(0, 102, 153));
        btinputnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/add jobrole.png"))); // NOI18N
        btinputnew.setBorderPainted(false);
        btinputnew.setContentAreaFilled(false);
        btinputnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btinputnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btinputnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btinputnewMouseExited(evt);
            }
        });
        btinputnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinputnewActionPerformed(evt);
            }
        });
        jPanel1.add(btinputnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 250));

        btSearch.setBackground(new java.awt.Color(0, 102, 153));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/search jobrole.png"))); // NOI18N
        btSearch.setBorderPainted(false);
        btSearch.setContentAreaFilled(false);
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchMouseExited(evt);
            }
        });
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 260, 250));

        btview.setBackground(new java.awt.Color(0, 102, 153));
        btview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/view report.png"))); // NOI18N
        btview.setBorderPainted(false);
        btview.setContentAreaFilled(false);
        btview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btviewMouseExited(evt);
            }
        });
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });
        jPanel1.add(btview, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 260, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("View Job Role Reports");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Search Job Roles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Input New Job Role");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btinputnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btinputnewMouseEntered
        btinputnew.setContentAreaFilled(true);
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_btinputnewMouseEntered

    private void btSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMouseEntered
        btSearch.setContentAreaFilled(true);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_btSearchMouseEntered

    private void btviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btviewMouseEntered
        btview.setContentAreaFilled(true);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_btviewMouseEntered

    private void btinputnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btinputnewMouseExited
        btinputnew.setContentAreaFilled(false);
        jLabel3.setForeground(Color.black);
    }//GEN-LAST:event_btinputnewMouseExited

    private void btSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMouseExited
        btSearch.setContentAreaFilled(false);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_btSearchMouseExited

    private void btviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btviewMouseExited
        btview.setContentAreaFilled(false);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_btviewMouseExited

    private void btinputnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinputnewActionPerformed
        if (inputnew == null) {
            inputnew=new input_jobrole();
            inputnew.setVisible(true);
        } else {
            inputnew.setVisible(true);
            inputnew=null;
        }
    }//GEN-LAST:event_btinputnewActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        if (search == null) {
            search=new search_jobrole();
            search.setVisible(true);
        } else {
            search.setVisible(true);
            search=null;
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        if (view == null) {
            view=new getReports();
            view.setVisible(true);
        } else {
            view.setVisible(true);
            view=null;
        }
    }//GEN-LAST:event_btviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btinputnew;
    private javax.swing.JButton btview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
