/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.loans;

import com.smsc.controller1.Empolyee_Controller;
import com.smsc.controller1.Grade_Controller;
import com.smsc.controller1.Jobrole_Controller;
import com.smsc.controller1.Jobrole_Details_Controller;
import com.smsc.controller1.Loan_Controller;
import com.smsc.model.Employee;
import com.smsc.model.Grade;
import com.smsc.model.Job_Role;
import com.smsc.model.Job_role_Detail;
import com.smsc.model.Loan;
import com.smsc.other.IdGenerator;
import com.smsc.other.Validation;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smsc
 */
public class create_loan extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    /**
     * Creates new form create_loan
     */
    public create_loan() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        loadLoanid();
        btCreateLoan.setEnabled(false);
    }
    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formatedDate = dateFormat.format(date);
        texDate.setText(formatedDate);
    }
    private void loadLoanid(){
        try {
            String newId = IdGenerator.getNewId("Loan", "Lid", "L");
            texID.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(create_loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        texLoanAmount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        texValidPreiod = new javax.swing.JTextField();
        texValue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        texNoOf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        texRate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btCreateLoan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        texEmployeeName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        texGradeName = new javax.swing.JTextField();
        texMaxloanAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        texJobRoleName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        texBasicSalary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texID = new javax.swing.JTextField();
        texDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texSearchEmployee = new org.jdesktop.swingx.JXSearchField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loan info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texLoanAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texLoanAmountActionPerformed(evt);
            }
        });
        jPanel7.add(texLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Loan Amount  :  ");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Valid Preiod  :  ");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 120, 30));

        texValidPreiod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texValidPreiod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texValidPreiodActionPerformed(evt);
            }
        });
        jPanel7.add(texValidPreiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 220, 30));

        texValue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 220, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Value of Instelment  :  ");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 170, 30));

        texNoOf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texNoOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNoOfActionPerformed(evt);
            }
        });
        jPanel7.add(texNoOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("No of Instalments  :  ");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Interest Rate  :  ");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));

        texRate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRateActionPerformed(evt);
            }
        });
        texRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texRateKeyReleased(evt);
            }
        });
        jPanel7.add(texRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("%");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        btCreateLoan.setBackground(new java.awt.Color(102, 102, 102));
        btCreateLoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btCreateLoan.setText("Create Loan");
        btCreateLoan.setBorderPainted(false);
        btCreateLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCreateLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateLoanActionPerformed(evt);
            }
        });
        jPanel7.add(btCreateLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 150, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 820, 180));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("View Loans");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 120, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Search Loan");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 140, 40));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee info..", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Employee Name :");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        texEmployeeName.setEditable(false);
        jPanel10.add(texEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Grade Name  : ");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 30));

        texGradeName.setEditable(false);
        jPanel10.add(texGradeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 240, 30));

        texMaxloanAmount.setEditable(false);
        jPanel10.add(texMaxloanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 240, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("MaxLoan Amount  :  ");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Job Role  :  ");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 30));

        texJobRoleName.setEditable(false);
        jPanel10.add(texJobRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Basic Salary  : ");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, 30));

        texBasicSalary.setEditable(false);
        jPanel10.add(texBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 240, 30));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 800, 150));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        jButton4.setText("_");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 840, 26));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Loan Fro Employee");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Loan ID  :  ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Date  :  ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, -1));

        texID.setEditable(false);
        texID.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.add(texID, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 140, -1));

        texDate.setEditable(false);
        texDate.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Enter Employee Nic  :  ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 40));

        texSearchEmployee.setFocusBehavior(org.jdesktop.swingx.prompt.PromptSupport.FocusBehavior.SHOW_PROMPT);
        texSearchEmployee.setSearchMode(org.jdesktop.swingx.JXSearchField.SearchMode.REGULAR);
        texSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texSearchEmployeeActionPerformed(evt);
            }
        });
        texSearchEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texSearchEmployeeKeyReleased(evt);
            }
        });
        jPanel4.add(texSearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 260));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 842, 602));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCreateLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateLoanActionPerformed
        createLoan();
    }//GEN-LAST:event_btCreateLoanActionPerformed

    private void texSearchEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texSearchEmployeeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(texSearchEmployee);
        }
    }//GEN-LAST:event_texSearchEmployeeKeyReleased

    private void texSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texSearchEmployeeActionPerformed
        searchLoan();
        texLoanAmount.requestFocus();
    }//GEN-LAST:event_texSearchEmployeeActionPerformed

    private void texLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texLoanAmountActionPerformed
        texValidPreiod.requestFocus();
    }//GEN-LAST:event_texLoanAmountActionPerformed

    private void texValidPreiodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texValidPreiodActionPerformed
        texNoOf.requestFocus();
    }//GEN-LAST:event_texValidPreiodActionPerformed

    private void texNoOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNoOfActionPerformed
        getvalue();
    }//GEN-LAST:event_texNoOfActionPerformed

    private void texRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRateActionPerformed
        btCreateLoan.setEnabled(true);
    }//GEN-LAST:event_texRateActionPerformed

    private void texRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texRateKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE || evt.getKeyCode() != KeyEvent.VK_PROPS) {
            Validation.validatenumber(texRate);
        }
    }//GEN-LAST:event_texRateKeyReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(create_loan.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateLoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField texBasicSalary;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texEmployeeName;
    private javax.swing.JTextField texGradeName;
    private javax.swing.JTextField texID;
    private javax.swing.JTextField texJobRoleName;
    private javax.swing.JTextField texLoanAmount;
    private javax.swing.JTextField texMaxloanAmount;
    private javax.swing.JTextField texNoOf;
    private javax.swing.JTextField texRate;
    private org.jdesktop.swingx.JXSearchField texSearchEmployee;
    private javax.swing.JTextField texValidPreiod;
    private javax.swing.JTextField texValue;
    // End of variables declaration//GEN-END:variables

    public void searchLoan(){
        String nic = texSearchEmployee.getText();
        Empolyee_Controller controller=new Empolyee_Controller();
        try {
            Employee Search_Employee_by_Nic = controller.Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Grade_Controller controller1=new Grade_Controller();
                Grade searchGrade_byGradeid = controller1.searchGrade_byGradeid(Search_Employee_by_Nic.getGid());
                if (searchGrade_byGradeid != null) {
                    Jobrole_Details_Controller details_Controller=new Jobrole_Details_Controller();
                    Job_role_Detail searchjobrole_details = details_Controller.searchjobrole_details(Search_Employee_by_Nic.getEid());
                    if (searchjobrole_details != null) {
                        Jobrole_Controller controller2=new Jobrole_Controller();
                        Job_Role searchjobrole_byjobroleid = controller2.searchjobrole_byjobroleid(searchjobrole_details.getJrid());
                        if (searchjobrole_byjobroleid != null) {
                            texJobRoleName.setText(searchjobrole_byjobroleid.getName());
                            texBasicSalary.setText(String.valueOf(searchGrade_byGradeid.getBasic_Salary()));
                            texMaxloanAmount.setText(String.valueOf(searchGrade_byGradeid.getMaxloan_Amount()));
                            texGradeName.setText(searchGrade_byGradeid.getName());
                            texEmployeeName.setText(Search_Employee_by_Nic.getSurename()+" "+Search_Employee_by_Nic.getLastname());
                        } else {
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(this, "Job Role Not Found in this Nic No   "+nic);
                        }
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Job Role Not Found in this Nic No   "+nic);
                    }
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Grade Not Found in this Nic No   "+nic);
                }
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Employee Not Found in this Nic No   "+nic);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(create_loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getvalue(){
        double amount = Double.parseDouble(texLoanAmount.getText());
        double noof = Double.parseDouble(texNoOf.getText());
        double value=amount/noof;
        texValue.setText(String.valueOf(value));
        texRate.requestFocus();
    }
    
    public void createLoan(){
         String lid = texID.getText();
        String nic = texSearchEmployee.getText();
        String date = texDate.getText();
        String preiod = texValidPreiod.getText();
        double Amount = Double.parseDouble(texLoanAmount.getText());
        String NoofInstalments = texNoOf.getText();
        double valueofinstelment = Double.parseDouble(texValue.getText());
        double rate = Double.parseDouble(texRate.getText());
        int pay=0;
        
        Empolyee_Controller controller=new Empolyee_Controller();
        try {
            Employee Search_Employee_by_Nic = controller.Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Loan loan=new Loan(lid, Search_Employee_by_Nic.getEid(), date, preiod, Amount, NoofInstalments, valueofinstelment, rate,pay);
                Loan_Controller controller1=new Loan_Controller();
                int addLoan = controller1.addLoan(loan);
                if (addLoan > 0) {
                    JOptionPane.showMessageDialog(this, "Loan Create Success To"+Search_Employee_by_Nic.getSurename()+" "+Search_Employee_by_Nic.getLastname());
                    texBasicSalary.setText("");
                    texEmployeeName.setText("");
                    texGradeName.setText("");
                    texJobRoleName.setText("");
                    texLoanAmount.setText("");
                    texMaxloanAmount.setText("");
                    texNoOf.setText("");
                    texRate.setText("");
                    texSearchEmployee.setText("");
                    texValidPreiod.setText("");
                    texValue.setText("");
                    loadLoanid();
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Loan Create Fail !! \n Please Check you input details and try again !!!");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(create_loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

