/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.loans;

import java.awt.Color;

/**
 *
 * @author smsc
 */
public class manage_loan extends javax.swing.JPanel {
    private create_loan loan=null;
    private searchLoan search=null;
    private View_All_Loans all_Loans=null;
    /**
     * Creates new form manage_loan
     */
    public manage_loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcreate = new javax.swing.JButton();
        btsearch = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        btreports = new javax.swing.JButton();
        jLabelsearch = new javax.swing.JLabel();
        jLabelview = new javax.swing.JLabel();
        jLabelcreate = new javax.swing.JLabel();
        jLabelreport = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btcreate.setBackground(new java.awt.Color(0, 102, 153));
        btcreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/add loan.png"))); // NOI18N
        btcreate.setBorderPainted(false);
        btcreate.setContentAreaFilled(false);
        btcreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btcreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btcreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btcreateMouseExited(evt);
            }
        });
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });
        jPanel1.add(btcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 250));

        btsearch.setBackground(new java.awt.Color(0, 102, 153));
        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/search loan.png"))); // NOI18N
        btsearch.setBorderPainted(false);
        btsearch.setContentAreaFilled(false);
        btsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btsearchMouseExited(evt);
            }
        });
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 260, 250));

        btview.setBackground(new java.awt.Color(0, 102, 153));
        btview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/view loan.png"))); // NOI18N
        btview.setBorderPainted(false);
        btview.setContentAreaFilled(false);
        btview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btviewMouseExited(evt);
            }
        });
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });
        jPanel1.add(btview, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 250, 250));

        btreports.setBackground(new java.awt.Color(0, 102, 153));
        btreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/view report.png"))); // NOI18N
        btreports.setBorderPainted(false);
        btreports.setContentAreaFilled(false);
        btreports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btreports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btreportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btreportsMouseExited(evt);
            }
        });
        jPanel1.add(btreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 260, 250));

        jLabelsearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelsearch.setText("Search Loan");
        jPanel1.add(jLabelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 260, -1));

        jLabelview.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelview.setText("View Loans");
        jPanel1.add(jLabelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 250, -1));

        jLabelcreate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelcreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcreate.setText("Create Loan");
        jPanel1.add(jLabelcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 260, -1));

        jLabelreport.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelreport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelreport.setText("Get Reports");
        jPanel1.add(jLabelreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btcreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcreateMouseEntered
        btcreate.setContentAreaFilled(true);
        jLabelcreate.setForeground(Color.white);
    }//GEN-LAST:event_btcreateMouseEntered

    private void btsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsearchMouseEntered
        btsearch.setContentAreaFilled(true);
        jLabelsearch.setForeground(Color.white);
    }//GEN-LAST:event_btsearchMouseEntered

    private void btviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btviewMouseEntered
        btview.setContentAreaFilled(true);
        jLabelview.setForeground(Color.white);
    }//GEN-LAST:event_btviewMouseEntered

    private void btreportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btreportsMouseEntered
        btreports.setContentAreaFilled(true);
        jLabelreport.setForeground(Color.white);
    }//GEN-LAST:event_btreportsMouseEntered

    private void btcreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcreateMouseExited
        btcreate.setContentAreaFilled(false);
        jLabelcreate.setForeground(Color.black);
    }//GEN-LAST:event_btcreateMouseExited

    private void btsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsearchMouseExited
        btsearch.setContentAreaFilled(false);
        jLabelsearch.setForeground(Color.black);
    }//GEN-LAST:event_btsearchMouseExited

    private void btviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btviewMouseExited
        btview.setContentAreaFilled(false);
        jLabelview.setForeground(Color.black);
    }//GEN-LAST:event_btviewMouseExited

    private void btreportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btreportsMouseExited
        btreports.setContentAreaFilled(false);
        jLabelreport.setForeground(Color.black);
    }//GEN-LAST:event_btreportsMouseExited

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        if (loan==null) {
            loan=new create_loan();
            loan.setVisible(true);
        } else {
            loan.setVisible(true);
            loan=null;
        }
    }//GEN-LAST:event_btcreateActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        if (search==null) {
            search=new searchLoan();
            search.setVisible(true);
        } else {
            search.setVisible(true);
            search=null;
        }
    }//GEN-LAST:event_btsearchActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        if (all_Loans==null) {
            all_Loans=new View_All_Loans();
            all_Loans.setVisible(true);
        } else {
            all_Loans.setVisible(true);
            all_Loans=null;
        }
    }//GEN-LAST:event_btviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JButton btreports;
    private javax.swing.JButton btsearch;
    private javax.swing.JButton btview;
    private javax.swing.JLabel jLabelcreate;
    private javax.swing.JLabel jLabelreport;
    private javax.swing.JLabel jLabelsearch;
    private javax.swing.JLabel jLabelview;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
