/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.loans;

import com.smsc.controller1.Empolyee_Controller;
import com.smsc.controller1.Grade_Controller;
import com.smsc.controller1.Jobrole_Controller;
import com.smsc.controller1.Jobrole_Details_Controller;
import com.smsc.controller1.Loan_Controller;
import com.smsc.controller1.Loan_Payment_Controller;
import com.smsc.model.Employee;
import com.smsc.model.Grade;
import com.smsc.model.Job_Role;
import com.smsc.model.Job_role_Detail;
import com.smsc.model.Loan;
import com.smsc.model.Loan_Payment;
import com.smsc.other.Validation;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smsc
 */
public class searchLoan extends javax.swing.JFrame {

    int xmouse;
    int ymouse;
    int selectedRow;
    private String Eid;
    private String Lid;
    private String Gid;
    private View_All_Loans all_Loans;

    /**
     * Creates new form searchLoan
     */
    public searchLoan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        texLoanAmount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        texValidPreiod = new javax.swing.JTextField();
        texValue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        texNoOf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        texRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        texEmployeeName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        texGradeName = new javax.swing.JTextField();
        texMaxloanAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        texJobRoleName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        texBasicSalary = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texsearchEmployee = new org.jdesktop.swingx.JXSearchField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabViewloans = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loan info", 1, 2));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texLoanAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Loan Amount  :  ");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Valid Preiod  :  ");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 30));

        texValidPreiod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texValidPreiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 220, 30));

        texValue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 220, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Value of Instelment  :  ");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 30));

        texNoOf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texNoOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 240, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("No of Instalments  :  ");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Interest Rate  :  ");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        texRate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(texRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("%");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 800, 170));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("View All Loans");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 150, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Remove");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 120, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, 120, 40));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee info..", 1, 2, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Employee Name :");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        texEmployeeName.setEditable(false);
        jPanel10.add(texEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Grade Name  : ");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 120, 30));

        texGradeName.setEditable(false);
        jPanel10.add(texGradeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 240, 30));

        texMaxloanAmount.setEditable(false);
        jPanel10.add(texMaxloanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 240, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("MaxLoan Amount  :  ");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Job Role  :  ");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 30));

        texJobRoleName.setEditable(false);
        jPanel10.add(texJobRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Basic Salary  : ");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, 30));

        texBasicSalary.setEditable(false);
        jPanel10.add(texBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 240, 30));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 800, 150));

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jButton5.setText("_");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 830, 26));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Employee Loans");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Enter Employee Nic  :  ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 230, -1));

        texsearchEmployee.setFocusBehavior(org.jdesktop.swingx.prompt.PromptSupport.FocusBehavior.SHOW_PROMPT);
        texsearchEmployee.setSearchMode(org.jdesktop.swingx.JXSearchField.SearchMode.REGULAR);
        texsearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texsearchEmployeeActionPerformed(evt);
            }
        });
        texsearchEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texsearchEmployeeKeyReleased(evt);
            }
        });
        jPanel4.add(texsearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, 30));

        tabViewloans.setBackground(new java.awt.Color(0, 102, 153));
        tabViewloans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan ID", "Date", "Amount", "No Of Instalments", "Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabViewloans.setOpaque(false);
        tabViewloans.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabViewloans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabViewloansMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabViewloans);
        tabViewloans.getColumnModel().getColumn(0).setResizable(false);
        tabViewloans.getColumnModel().getColumn(1).setResizable(false);
        tabViewloans.getColumnModel().getColumn(2).setResizable(false);
        tabViewloans.getColumnModel().getColumn(3).setResizable(false);
        tabViewloans.getColumnModel().getColumn(4).setResizable(false);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 800, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, 703));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (all_Loans == null) {
            all_Loans = new View_All_Loans();
            all_Loans.setVisible(true);
        } else {
            all_Loans.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setState(searchLoan.ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void texsearchEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texsearchEmployeeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(texsearchEmployee);
        }
    }//GEN-LAST:event_texsearchEmployeeKeyReleased

    private void texsearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texsearchEmployeeActionPerformed
        searchEmplyee();
    }//GEN-LAST:event_texsearchEmployeeActionPerformed

    private void tabViewloansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabViewloansMouseClicked
        selectedRow = tabViewloans.getSelectedRow();
        getvalue();
    }//GEN-LAST:event_tabViewloansMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getifUpdate();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new searchLoan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabViewloans;
    private javax.swing.JTextField texBasicSalary;
    private javax.swing.JTextField texEmployeeName;
    private javax.swing.JTextField texGradeName;
    private javax.swing.JTextField texJobRoleName;
    private javax.swing.JTextField texLoanAmount;
    private javax.swing.JTextField texMaxloanAmount;
    private javax.swing.JTextField texNoOf;
    private javax.swing.JTextField texRate;
    private javax.swing.JTextField texValidPreiod;
    private javax.swing.JTextField texValue;
    private org.jdesktop.swingx.JXSearchField texsearchEmployee;
    // End of variables declaration//GEN-END:variables

    private void searchEmplyee() {
        String nic = texsearchEmployee.getText();
        try {
            Employee Search_Employee_by_Nic = new Empolyee_Controller().Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Eid = Search_Employee_by_Nic.getEid();
                Gid = Search_Employee_by_Nic.getGid();
                ArrayList<Loan> searchLoans_byemployeeid = new Loan_Controller().searchLoans_byemployeeid(Eid);
                DefaultTableModel tableModel = (DefaultTableModel) tabViewloans.getModel();
                tableModel.setRowCount(0);
                for (Loan loan : searchLoans_byemployeeid) {
                    Lid = loan.getLid();
                    double paymentValue = getPaymentValue();
                    Object[] row = {loan.getLid(), loan.getDate(), loan.getAmount(), loan.getNo_of_Instalments(), paymentValue};
                    tableModel.addRow(row);
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(searchLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private double getPaymentValue() {
        double amount = 0.0;
        try {
            ArrayList<Loan_Payment> searchLoanPayment_byLoanid = new Loan_Payment_Controller().searchLoanPayment_byLoanid(Lid);
            for (Loan_Payment loan_Payment : searchLoanPayment_byLoanid) {
                if (loan_Payment.getPay() == 1) {
                    amount = amount + loan_Payment.getAmount();
                }
            }
            return amount;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(searchLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        return amount;
    }

    private void getvalue() {
        try {
            String id = tabViewloans.getValueAt(selectedRow, 0).toString();
            String loanAmount = tabViewloans.getValueAt(selectedRow, 2).toString();
            String noOf = tabViewloans.getValueAt(selectedRow, 3).toString();
                Loan searchLoans_byloanid = new Loan_Controller().searchLoans_byloanid(id);
                if (searchLoans_byloanid != null) {
                        texLoanAmount.setText(loanAmount);
                        texNoOf.setText(noOf);
                        texValidPreiod.setText(searchLoans_byloanid.getValid_Preiod());
                        texRate.setText(String.valueOf(searchLoans_byloanid.getInterest_Rate()));
                        texValue.setText(String.valueOf(searchLoans_byloanid.getValue_of_Instelment()));
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Job Loan Not Found !!!");
                    }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(searchLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getifUpdate() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you want to Update This Grade ?");
        if (confirm == JOptionPane.YES_OPTION) {
            upgrade();
        }
    }

    private void upgrade() {
        
    }
}
