/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.setings;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import com.smsc.controller1.User_Details_Controller;
import com.smsc.model.User_Details;
import com.smsc.view.main.login;

/**
 *
 * @author smsc
 */
public class createaccount extends javax.swing.JFrame {
    private String pass;
    /**
     * Creates new form createaccount
     */
    public createaccount() {
        initComponents();
        btDone.setEnabled(false);
        setLocationRelativeTo(null);
        //this.setIconImage(new ImageIcon(getClass().getResource("/Photos/my system logo.png")).getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texusername = new javax.swing.JTextField();
        texanswer = new javax.swing.JTextField();
        texrepassword = new javax.swing.JPasswordField();
        texpassword = new javax.swing.JPasswordField();
        texsecuritycode = new javax.swing.JTextField();
        btDone = new javax.swing.JButton();
        User_id2 = new javax.swing.JLabel();
        User_id4 = new javax.swing.JLabel();
        User_id5 = new javax.swing.JLabel();
        User_id6 = new javax.swing.JLabel();
        User_id7 = new javax.swing.JLabel();
        toptexLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texusername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texusernameActionPerformed(evt);
            }
        });
        jPanel1.add(texusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 320, 30));

        texanswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texanswerActionPerformed(evt);
            }
        });
        jPanel1.add(texanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 430, 30));

        texrepassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texrepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texrepasswordActionPerformed(evt);
            }
        });
        jPanel1.add(texrepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 240, 30));

        texpassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(texpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 30));

        texsecuritycode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texsecuritycode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texsecuritycodeActionPerformed(evt);
            }
        });
        jPanel1.add(texsecuritycode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 30));

        btDone.setBackground(new java.awt.Color(102, 102, 102));
        btDone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btDone.setText("Done Create");
        btDone.setBorderPainted(false);
        btDone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, 30));

        User_id2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        User_id2.setForeground(new java.awt.Color(51, 0, 102));
        User_id2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User_id2.setText("User Name  : ");
        jPanel1.add(User_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 30));

        User_id4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        User_id4.setForeground(new java.awt.Color(51, 0, 102));
        User_id4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User_id4.setText("Password  : ");
        jPanel1.add(User_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 30));

        User_id5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        User_id5.setForeground(new java.awt.Color(51, 0, 102));
        User_id5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User_id5.setText("RE Password  : ");
        jPanel1.add(User_id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        User_id6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        User_id6.setForeground(new java.awt.Color(51, 0, 102));
        User_id6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User_id6.setText("Security Code  : ");
        jPanel1.add(User_id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 30));

        User_id7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        User_id7.setForeground(new java.awt.Color(51, 0, 102));
        User_id7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User_id7.setText("Answer  : ");
        jPanel1.add(User_id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, 30));

        toptexLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        toptexLabel.setForeground(new java.awt.Color(0, 0, 102));
        toptexLabel.setText("Create New Account");
        jPanel1.add(toptexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texusernameActionPerformed
        texpassword.requestFocus();
    }//GEN-LAST:event_texusernameActionPerformed

    private void texpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texpasswordActionPerformed
        texrepassword.requestFocus();
        pass=texpassword.getText();
    }//GEN-LAST:event_texpasswordActionPerformed

    private void texrepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texrepasswordActionPerformed
        if (pass.equals(texrepassword.getText())) {
        texpassword.setBorder(new LineBorder(Color.green,3));
        texrepassword.setBorder(new LineBorder(Color.green,3));
        texsecuritycode.requestFocus();
        } else {
        texpassword.setBorder(new LineBorder(Color.red, 3));
        texrepassword.setBorder(new LineBorder(Color.red,3));
        texrepassword.setText("");
        texpassword.requestFocus();
        }
    }//GEN-LAST:event_texrepasswordActionPerformed

    private void texanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texanswerActionPerformed
        btDone.setEnabled(true);
    }//GEN-LAST:event_texanswerActionPerformed

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
        String uid = "u002";
        String username = texusername.getText();
        String password = texrepassword.getText().toString();
        String security = texsecuritycode.getText();
        String answer = texanswer.getText();
        User_Details user_Details=new User_Details(uid, username, password, security, answer);
        User_Details_Controller user_Details_Controller=new User_Details_Controller();
        try {
            int addUser = user_Details_Controller.addUser(user_Details);
            if (addUser > 0) {
                JOptionPane.showMessageDialog(this,"Your New Account Created Successfully !!!!");
                new login().setVisible(true);
                this.setVisible(false);
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this,"Your New Account Create Fail !!!!!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(createaccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDoneActionPerformed

    private void texsecuritycodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texsecuritycodeActionPerformed
        texanswer.requestFocus();
    }//GEN-LAST:event_texsecuritycodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel User_id2;
    private javax.swing.JLabel User_id4;
    private javax.swing.JLabel User_id5;
    private javax.swing.JLabel User_id6;
    private javax.swing.JLabel User_id7;
    private javax.swing.JButton btDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField texanswer;
    private javax.swing.JPasswordField texpassword;
    private javax.swing.JPasswordField texrepassword;
    private javax.swing.JTextField texsecuritycode;
    private javax.swing.JTextField texusername;
    private javax.swing.JLabel toptexLabel;
    // End of variables declaration//GEN-END:variables
}
