/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.departmant;

import com.smsc.controller1.Department_Controller;
import com.smsc.model.Department;
import com.smsc.view.main.home_page;
import java.awt.Cursor;
import static java.awt.Frame.WAIT_CURSOR;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author smsc
 */
public class view_department extends javax.swing.JFrame {
    private int selectedRow;
    private String Deid;
    int xmouse;
    int ymouse;
    /**
     * Creates new form view_department
     */
    public view_department() {
        initComponents();
        setLocationRelativeTo(null);
        loadDepartment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        departmentnameLabel1 = new javax.swing.JLabel();
        texDepartmentName = new javax.swing.JTextField();
        texDepartmentBuliding = new javax.swing.JTextField();
        buildingLabel1 = new javax.swing.JLabel();
        deletedepartment = new javax.swing.JButton();
        updatedepartment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabview = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        btmini = new javax.swing.JButton();
        btReload = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        departmentnameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        departmentnameLabel1.setForeground(new java.awt.Color(0, 0, 102));
        departmentnameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        departmentnameLabel1.setText("Department Name  :  ");
        jPanel3.add(departmentnameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 210, -1));

        texDepartmentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texDepartmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texDepartmentNameActionPerformed(evt);
            }
        });
        jPanel3.add(texDepartmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 190, 30));

        texDepartmentBuliding.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texDepartmentBuliding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texDepartmentBulidingActionPerformed(evt);
            }
        });
        jPanel3.add(texDepartmentBuliding, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 150, 30));

        buildingLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        buildingLabel1.setForeground(new java.awt.Color(0, 0, 102));
        buildingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buildingLabel1.setText("Department Building  :  ");
        jPanel3.add(buildingLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 260, -1));

        deletedepartment.setBackground(new java.awt.Color(102, 102, 102));
        deletedepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deletedepartment.setText("Remove");
        deletedepartment.setBorderPainted(false);
        deletedepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletedepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedepartmentActionPerformed(evt);
            }
        });
        jPanel3.add(deletedepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 160, 40));

        updatedepartment.setBackground(new java.awt.Color(102, 102, 102));
        updatedepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updatedepartment.setText("Update ");
        updatedepartment.setBorderPainted(false);
        updatedepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatedepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedepartmentActionPerformed(evt);
            }
        });
        jPanel3.add(updatedepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 160, 40));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department Name", "Buliding"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabview);
        if (tabview.getColumnModel().getColumnCount() > 0) {
            tabview.getColumnModel().getColumn(0).setResizable(false);
            tabview.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 430, 210));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Department");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 40, 610, -1));

        btexit.setText("X");
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btexitMouseClicked(evt);
            }
        });
        jPanel3.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        btmini.setText("_");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        jPanel3.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        btReload.setBackground(new java.awt.Color(102, 102, 102));
        btReload.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btReload.setText("Reload");
        btReload.setBorderPainted(false);
        btReload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReloadActionPerformed(evt);
            }
        });
        jPanel3.add(btReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 210, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 526));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texDepartmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texDepartmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texDepartmentNameActionPerformed

    private void texDepartmentBulidingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texDepartmentBulidingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texDepartmentBulidingActionPerformed

    private void updatedepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedepartmentActionPerformed
        if (selectedRow > -1) {
            updateDepartment();
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row !!!!!");
        }
    }//GEN-LAST:event_updatedepartmentActionPerformed

    private void deletedepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedepartmentActionPerformed
        if (selectedRow > -1) {
            removeDepartment();
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row !!!!!");
        }
    }//GEN-LAST:event_deletedepartmentActionPerformed

    private void btexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btexitMouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        this.setState(view_department.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void btReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReloadActionPerformed
        loadDepartment();
    }//GEN-LAST:event_btReloadActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        selectedRow = tabview.getSelectedRow();
        getvalue();
        loadtxt();
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabviewMouseClicked
        selectedRow = tabview.getSelectedRow();
        getvalue();
        loadtxt();
    }//GEN-LAST:event_tabviewMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getback();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReload;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btmini;
    private javax.swing.JLabel buildingLabel1;
    private javax.swing.JButton deletedepartment;
    private javax.swing.JLabel departmentnameLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabview;
    private javax.swing.JTextField texDepartmentBuliding;
    private javax.swing.JTextField texDepartmentName;
    private javax.swing.JButton updatedepartment;
    // End of variables declaration//GEN-END:variables

    private void loadDepartment() {
        try {
            ArrayList<Department> _All_Department = new Department_Controller().get_All_Department();
            DefaultTableModel dtm=(DefaultTableModel) tabview.getModel();
            dtm.setRowCount(0);
            for(Department department : _All_Department){
                Object[] row={department.getName(),department.getBuilding()};
                dtm.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(view_department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateDepartment() {
        String buliding = texDepartmentBuliding.getText();
        String name = texDepartmentName.getText();
        Department department=new Department(Deid, name, buliding);
        try {
            int update_Department = new Department_Controller().update_Department(department);
            if (update_Department > 0) {
                JOptionPane.showMessageDialog(this, "Department Detail Update Success !!!");
                texDepartmentBuliding.setText("");
                texDepartmentName.setText("");
                loadDepartment();
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "There are some mistakes in you enter details\n Please Check !!!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(view_department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getvalue() {
        String deName = tabview.getValueAt(selectedRow, 0).toString();
    try {
            Department search_Department_by_Name = new Department_Controller().search_Department_by_Name(deName);
            Deid=search_Department_by_Name.getDid();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(view_department.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    private void loadtxt() {
        String name = tabview.getValueAt(selectedRow, 0).toString();
        String bilding = tabview.getValueAt(selectedRow, 1).toString();
        texDepartmentBuliding.setText(bilding);
        texDepartmentName.setText(name);
    }

    private void removeDepartment() {
        try {
            int deleteDepartment = new Department_Controller().deleteDepartment(Deid);
            if (deleteDepartment > 0) {
                JOptionPane.showMessageDialog(this, "Department Remove Success !!!");
                texDepartmentBuliding.setText("");
                texDepartmentName.setText("");
                loadDepartment();
            } else {
                int x=0;
                for (int i = 0; i < 11; i++) {
                    x=x+i;
                }
                while(x==20){
                    this.setCursor(new Cursor(WAIT_CURSOR));
                }
                JOptionPane.showMessageDialog(this, "Department Remove Fail !!!\n Try Again !!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(view_department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getback() {
        Object[] options = {"Cancel", "Home Page", "Input Department"};
                int showOptionDialog = JOptionPane.showOptionDialog(this, "Back to Where ?", "Qustion", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, new ImageIcon("./src/com/smsc/view/photos1/help.PNG"), options, options[0]);
                if (showOptionDialog == 1) {
                    new home_page().setVisible(true);
                    this.dispose();
                } else if (showOptionDialog == 2) {
                    new input_department().setVisible(true);
                    this.dispose();
                }
        
    }
}
