/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.leaves;

import com.smsc.controller1.Department_Controller;
import com.smsc.controller1.Department_Details_Controller;
import com.smsc.controller1.Empolyee_Controller;
import com.smsc.controller1.Grade_Controller;
import com.smsc.controller1.Jobrole_Controller;
import com.smsc.controller1.Jobrole_Details_Controller;
import com.smsc.model.Department;
import com.smsc.model.Department_Detail;
import com.smsc.model.Employee;
import com.smsc.model.Grade;
import com.smsc.model.Job_Role;
import com.smsc.model.Job_role_Detail;
import com.smsc.view.half_day.Manage_Employee_HalfDay;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smsc
 */
public class Manage_Employee_Leaves extends javax.swing.JFrame {
    private String Eid;
    private String Did;
    private String Jrid;
    private String Gid;
    /**
     * Creates new form Manage_Employee_Leaves
     */
    public Manage_Employee_Leaves() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        btHalfDay = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labDate = new javax.swing.JLabel();
        texDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labEmployeeNic = new javax.swing.JLabel();
        texEmployeeNic = new org.jdesktop.swingx.JXSearchField();
        LeaveinfoPanel = new javax.swing.JPanel();
        labLeaveDate = new javax.swing.JLabel();
        labLeaveCount = new javax.swing.JLabel();
        SpinnerLeaveCount = new javax.swing.JSpinner();
        labDayNumber = new javax.swing.JLabel();
        labDay = new javax.swing.JLabel();
        CalendarComboLeaveDay = new org.freixas.jcalendar.JCalendarCombo();
        btGenerate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabViewLeaves = new javax.swing.JTable();
        btRemove = new javax.swing.JButton();
        employeeInfoPanel = new javax.swing.JPanel();
        labEmployeeJobRole = new javax.swing.JLabel();
        labEmployeeGrade = new javax.swing.JLabel();
        labEmployeeDepartment = new javax.swing.JLabel();
        texEmployeeGrade = new javax.swing.JTextField();
        texEmployeeDepartment = new javax.swing.JTextField();
        texEmployeeJobrole = new javax.swing.JTextField();
        btSearchEmployee = new javax.swing.JButton();
        EmployeeAttendancePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labPresentdays = new javax.swing.JLabel();
        labAbsentdays = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btcreateLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHalfDay.setBackground(new java.awt.Color(102, 102, 102));
        btHalfDay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btHalfDay.setText("Click To Create Half Day Leave");
        btHalfDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btHalfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 880, 10));

        labDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labDate.setForeground(new java.awt.Color(0, 0, 102));
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labDate.setText("Date  :  ");
        jPanel4.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, 40));

        texDate.setEditable(false);
        texDate.setFont(new java.awt.Font("Pump Demi Bold LET", 0, 24)); // NOI18N
        texDate.setForeground(new java.awt.Color(0, 0, 102));
        texDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 180, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Leave");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 40));

        labEmployeeNic.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeNic.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeNic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmployeeNic.setText("Enter Employee NIC  : ");
        jPanel4.add(labEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        texEmployeeNic.setSearchMode(null);
        jPanel4.add(texEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 30));

        LeaveinfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeaveinfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leave info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        LeaveinfoPanel.setOpaque(false);
        LeaveinfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labLeaveDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labLeaveDate.setForeground(new java.awt.Color(0, 0, 102));
        labLeaveDate.setText("Leave Date  : ");
        LeaveinfoPanel.add(labLeaveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        labLeaveCount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labLeaveCount.setForeground(new java.awt.Color(0, 0, 102));
        labLeaveCount.setText("Leave Count  :  ");
        LeaveinfoPanel.add(labLeaveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        SpinnerLeaveCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SpinnerLeaveCount.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        LeaveinfoPanel.add(SpinnerLeaveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, -1));

        labDayNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labDayNumber.setForeground(new java.awt.Color(0, 0, 102));
        labDayNumber.setText("1 ");
        LeaveinfoPanel.add(labDayNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 90, 20, 30));

        labDay.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labDay.setForeground(new java.awt.Color(0, 0, 102));
        labDay.setText("Day");
        LeaveinfoPanel.add(labDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 50, 30));

        CalendarComboLeaveDay.setBackground(new java.awt.Color(255, 255, 255));
        LeaveinfoPanel.add(CalendarComboLeaveDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, 30));

        btGenerate.setBackground(new java.awt.Color(102, 102, 102));
        btGenerate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btGenerate.setText("Genarete");
        btGenerate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeaveinfoPanel.add(btGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, 30));

        tabViewLeaves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "No Of Leaves"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabViewLeaves);
        if (tabViewLeaves.getColumnModel().getColumnCount() > 0) {
            tabViewLeaves.getColumnModel().getColumn(0).setResizable(false);
            tabViewLeaves.getColumnModel().getColumn(1).setResizable(false);
        }

        LeaveinfoPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 470, 120));

        btRemove.setBackground(new java.awt.Color(102, 102, 102));
        btRemove.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRemove.setText("Remove");
        btRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeaveinfoPanel.add(btRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jPanel4.add(LeaveinfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 580, 330));

        employeeInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        employeeInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        employeeInfoPanel.setOpaque(false);
        employeeInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labEmployeeJobRole.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeJobRole.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeJobRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeJobRole.setText("Employee Job Role  : ");
        employeeInfoPanel.add(labEmployeeJobRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 30));

        labEmployeeGrade.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeGrade.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeGrade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeGrade.setText("Employee Grade  : ");
        employeeInfoPanel.add(labEmployeeGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 30));

        labEmployeeDepartment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeDepartment.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeDepartment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeDepartment.setText("Employee Department  : ");
        employeeInfoPanel.add(labEmployeeDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        texEmployeeGrade.setEditable(false);
        texEmployeeGrade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeGrade.setForeground(new java.awt.Color(0, 0, 102));
        employeeInfoPanel.add(texEmployeeGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, 30));

        texEmployeeDepartment.setEditable(false);
        texEmployeeDepartment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeDepartment.setForeground(new java.awt.Color(0, 0, 102));
        employeeInfoPanel.add(texEmployeeDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, 30));

        texEmployeeJobrole.setEditable(false);
        texEmployeeJobrole.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeJobrole.setForeground(new java.awt.Color(0, 0, 102));
        employeeInfoPanel.add(texEmployeeJobrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 230, 30));

        jPanel4.add(employeeInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 440, 180));

        btSearchEmployee.setBackground(new java.awt.Color(102, 102, 102));
        btSearchEmployee.setText("Search");
        btSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btSearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 30));

        EmployeeAttendancePanel.setBackground(new java.awt.Color(255, 255, 255));
        EmployeeAttendancePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        EmployeeAttendancePanel.setOpaque(false);
        EmployeeAttendancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("No Of Absent Days  : ");
        EmployeeAttendancePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 30));

        labPresentdays.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labPresentdays.setForeground(new java.awt.Color(0, 0, 102));
        labPresentdays.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPresentdays.setText("No Of Present Days  : ");
        EmployeeAttendancePanel.add(labPresentdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        labAbsentdays.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labAbsentdays.setForeground(new java.awt.Color(0, 0, 102));
        labAbsentdays.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labAbsentdays.setText("No Of Absent Days  : ");
        EmployeeAttendancePanel.add(labAbsentdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No Of Absent Days  : ");
        EmployeeAttendancePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 30));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        EmployeeAttendancePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        EmployeeAttendancePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        EmployeeAttendancePanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 30));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 102));
        EmployeeAttendancePanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 30));

        jPanel4.add(EmployeeAttendancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 410, 180));

        btcreateLeave.setText("jButton1");
        jPanel4.add(btcreateLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 140, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee Leaves");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swme/View/photos1/leaves copy.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 680));

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Employee_Leaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo CalendarComboLeaveDay;
    private javax.swing.JPanel EmployeeAttendancePanel;
    private javax.swing.JPanel LeaveinfoPanel;
    private javax.swing.JSpinner SpinnerLeaveCount;
    private javax.swing.JButton btGenerate;
    private javax.swing.JButton btHalfDay;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSearchEmployee;
    private javax.swing.JButton btcreateLeave;
    private javax.swing.JPanel employeeInfoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labAbsentdays;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDay;
    private javax.swing.JLabel labDayNumber;
    private javax.swing.JLabel labEmployeeDepartment;
    private javax.swing.JLabel labEmployeeGrade;
    private javax.swing.JLabel labEmployeeJobRole;
    private javax.swing.JLabel labEmployeeNic;
    private javax.swing.JLabel labLeaveCount;
    private javax.swing.JLabel labLeaveDate;
    private javax.swing.JLabel labPresentdays;
    private javax.swing.JTable tabViewLeaves;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texEmployeeDepartment;
    private javax.swing.JTextField texEmployeeGrade;
    private javax.swing.JTextField texEmployeeJobrole;
    private org.jdesktop.swingx.JXSearchField texEmployeeNic;
    // End of variables declaration//GEN-END:variables

    private void searchEmployee() {
        try {
            String nic = texEmployeeNic.getText();
            Employee Search_Employee_by_Nic = new Empolyee_Controller().Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Eid=Search_Employee_by_Nic.getEid();
                Grade searchGrade_byGradeid = new Grade_Controller().searchGrade_byGradeid(Search_Employee_by_Nic.getGid());
                if (searchGrade_byGradeid != null) {
                    Gid=searchGrade_byGradeid.getGid();
                    Job_role_Detail searchjobrole_details = new Jobrole_Details_Controller().searchjobrole_details(Search_Employee_by_Nic.getEid());
                    if (searchjobrole_details != null) {
                        Job_Role searchjobrole_byjobroleid = new Jobrole_Controller().searchjobrole_byjobroleid(searchjobrole_details.getJrid());
                        if (searchjobrole_byjobroleid != null) {
                            Jrid=searchjobrole_byjobroleid.getJrid();
                            Department_Detail searchDepartment_Detailseid = new Department_Details_Controller().searchDepartment_Detailseid(Search_Employee_by_Nic.getEid());
                            if (searchDepartment_Detailseid != null) {
                                Department search_Department_by_id = new Department_Controller().search_Department_by_id(searchDepartment_Detailseid.getDid());
                                if (search_Department_by_id != null) {
                                    Did=search_Department_by_id.getDid();
                                    texEmployeeDepartment.setText(search_Department_by_id.getName());
                                    texEmployeeGrade.setText(searchGrade_byGradeid.getName());
                                    texEmployeeJobrole.setText(searchjobrole_byjobroleid.getName());
                                } else {
                                    Toolkit.getDefaultToolkit().beep();
                                    JOptionPane.showMessageDialog(this, "No Department Found !!!");
                                }
                            } else {
                                Toolkit.getDefaultToolkit().beep();
                                JOptionPane.showMessageDialog(this, "No Department Found !!!");
                            }
                        } else {
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(this, "No JobRole Found !!!");
                        }
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "No JobRole Found !!!");
                    }
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "No Grade Found !!!");
                }
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Employee Found In INC No !!!"+nic);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
