/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.damage;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import com.smsc.controller1.Damage_Controller;
import com.smsc.controller1.Damage_Description_Controller;
import com.smsc.controller1.Empolyee_Controller;
import com.smsc.model.Damage;
import com.smsc.model.Damage_Description;
import com.smsc.model.Employee;
import com.smsc.other.IdGenerator;
import com.smsc.other.Validation;

/**
 *
 * @author smsc
 */
public class InputDamages extends javax.swing.JFrame {
    private String DamageDiscrptionid;
    private SearchDamage searchDamage=null;
    int xmouse;
    int ymouse;
    /**
     * Creates new form InputDamages
     */
    public InputDamages() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();    
        try {
            loadid();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InputDamages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formatedDate = dateFormat.format(date);
        textDate.setText(formatedDate);
    }
    private void loadid() throws ClassNotFoundException, SQLException{
        String newId;
        String newId1;
        newId = IdGenerator.getNewId("Damage", "Deid", "D");
        texDamageid.setText(newId);
        newId1 = IdGenerator.getNewId("Damage_Description", "Ddid", "DD");
        DamageDiscrptionid=newId1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabviewdescription = new javax.swing.JTable();
        labDate = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        labEmployeeNic = new javax.swing.JLabel();
        labLost = new javax.swing.JLabel();
        SearchFiEmployeeNic = new org.jdesktop.swingx.JXSearchField();
        textLost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabViewPastDamage = new javax.swing.JTable();
        btSearchDamage = new javax.swing.JButton();
        btAddDamage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labDamageid = new javax.swing.JLabel();
        texDamageid = new javax.swing.JTextField();
        texDescription = new javax.swing.JTextField();
        labDescription = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Damage");
        setUndecorated(true);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabviewdescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Damage Cost", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabviewdescription);
        if (tabviewdescription.getColumnModel().getColumnCount() > 0) {
            tabviewdescription.getColumnModel().getColumn(0).setResizable(false);
            tabviewdescription.getColumnModel().getColumn(1).setResizable(false);
            tabviewdescription.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 550, 160));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 580, 190));

        labDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(0, 0, 51));
        labDate.setText("Date  :  ");
        jPanel1.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, 30));

        textDate.setEditable(false);
        textDate.setBackground(new java.awt.Color(0, 153, 204));
        textDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textDate.setForeground(new java.awt.Color(0, 0, 102));
        textDate.setBorder(null);
        jPanel1.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 140, 30));

        labEmployeeNic.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeNic.setForeground(new java.awt.Color(0, 0, 51));
        labEmployeeNic.setText("Employee Nic  : ");
        jPanel1.add(labEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        labLost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labLost.setForeground(new java.awt.Color(0, 0, 51));
        labLost.setText("Damage Cost  :  ");
        jPanel1.add(labLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        SearchFiEmployeeNic.setForeground(new java.awt.Color(0, 0, 51));
        SearchFiEmployeeNic.setSearchMode(org.jdesktop.swingx.JXSearchField.SearchMode.REGULAR);
        SearchFiEmployeeNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFiEmployeeNicActionPerformed(evt);
            }
        });
        SearchFiEmployeeNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFiEmployeeNicKeyReleased(evt);
            }
        });
        jPanel1.add(SearchFiEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, -1));

        textLost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textLost.setForeground(new java.awt.Color(0, 0, 51));
        textLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLostActionPerformed(evt);
            }
        });
        textLost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textLostKeyReleased(evt);
            }
        });
        jPanel1.add(textLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 240, 30));

        tabViewPastDamage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Damage Date", "Damage Lost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabViewPastDamage.setOpaque(false);
        jScrollPane1.setViewportView(tabViewPastDamage);
        if (tabViewPastDamage.getColumnModel().getColumnCount() > 0) {
            tabViewPastDamage.getColumnModel().getColumn(0).setResizable(false);
            tabViewPastDamage.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 360, 140));

        btSearchDamage.setBackground(new java.awt.Color(102, 102, 102));
        btSearchDamage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btSearchDamage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/search.png"))); // NOI18N
        btSearchDamage.setText("Search Damage");
        btSearchDamage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearchDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchDamageActionPerformed(evt);
            }
        });
        jPanel1.add(btSearchDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 160, 40));

        btAddDamage.setBackground(new java.awt.Color(102, 102, 102));
        btAddDamage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btAddDamage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/Attendance/accept.png"))); // NOI18N
        btAddDamage.setText("Input Damage");
        btAddDamage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDamageActionPerformed(evt);
            }
        });
        jPanel1.add(btAddDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 160, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SMSC Payroll");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 240, -1));

        labDamageid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labDamageid.setForeground(new java.awt.Color(0, 0, 102));
        labDamageid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labDamageid.setText("Damage ID  : ");
        jPanel1.add(labDamageid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        texDamageid.setEditable(false);
        texDamageid.setBackground(new java.awt.Color(0, 153, 204));
        texDamageid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texDamageid.setForeground(new java.awt.Color(0, 0, 102));
        texDamageid.setBorder(null);
        jPanel1.add(texDamageid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 30));

        texDescription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texDescription.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(texDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 370, 30));

        labDescription.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labDescription.setForeground(new java.awt.Color(0, 0, 51));
        labDescription.setText("Damage Description  :  ");
        jPanel1.add(labDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Input Damages");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, -1));

        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setOpaque(true);
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 802, 548));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchFiEmployeeNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFiEmployeeNicActionPerformed
        String nic = SearchFiEmployeeNic.getText();
        search(nic);
    }//GEN-LAST:event_SearchFiEmployeeNicActionPerformed

    private void btAddDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDamageActionPerformed
        inputdamage();    
    }//GEN-LAST:event_btAddDamageActionPerformed

    private void btSearchDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchDamageActionPerformed
        if (searchDamage == null) {
            searchDamage=new SearchDamage();
            searchDamage.setVisible(true);
        } else {
            searchDamage.setVisible(true);
            searchDamage=null;
        }
    }//GEN-LAST:event_btSearchDamageActionPerformed

    private void SearchFiEmployeeNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFiEmployeeNicKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(SearchFiEmployeeNic);
        }
    }//GEN-LAST:event_SearchFiEmployeeNicKeyReleased

    private void textLostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLostKeyReleased
        String lost = textLost.getText();
        boolean match=lost.matches("[\\d]*");
        String replaceAll = lost.replaceAll("[\\D]", "");
        textLost.setText(replaceAll);
    }//GEN-LAST:event_textLostKeyReleased

    private void textLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLostActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(InputDamages.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDamages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDamages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDamages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDamages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDamages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXSearchField SearchFiEmployeeNic;
    private javax.swing.JButton btAddDamage;
    private javax.swing.JButton btSearchDamage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labDamageid;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDescription;
    private javax.swing.JLabel labEmployeeNic;
    private javax.swing.JLabel labLost;
    private javax.swing.JTable tabViewPastDamage;
    private javax.swing.JTable tabviewdescription;
    private javax.swing.JTextField texDamageid;
    private javax.swing.JTextField texDescription;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textLost;
    // End of variables declaration//GEN-END:variables

    private void inputdamage(String Damageid, String date, String nic, int lost, String description) {
        Empolyee_Controller ec = new Empolyee_Controller();
            try {
                Employee Search_Employee_by_Nic = ec.Search_Employee_by_Nic(nic);
                if (Search_Employee_by_Nic != null) {
                    Damage damage = new Damage(Damageid, Search_Employee_by_Nic.getEid(), date, lost);
                    Damage_Controller damage_Controller = new Damage_Controller();
                    int addDamage = damage_Controller.addDamage(damage);
                    if (addDamage > 0) {
                        Damage_Description damage_Description = new Damage_Description(DamageDiscrptionid, Damageid, description);
                        Damage_Description_Controller description_Controller = new Damage_Description_Controller();
                        int addDescription = description_Controller.addDescription(damage_Description);
                        if (addDescription > 0) {
                            JOptionPane.showMessageDialog(this, "Damage Input Success !");
                            loadid();
                            DefaultTableModel dtm=(DefaultTableModel) tabviewdescription.getModel();
                            Object[]row={(Search_Employee_by_Nic.getSurename()+Search_Employee_by_Nic.getLastname()),textLost.getText(),texDescription.getText()};
                            dtm.addRow(row);
                            SearchFiEmployeeNic.setText("");
                            texDescription.setText("");
                            textLost.setText("");
                        } else {
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(this, "Description Input Fail !");
                        }
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Damage Input Fail !");
                    }
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InputDamages.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    private void search(String nic) {
        Empolyee_Controller ec=new Empolyee_Controller();
        try {
            Employee Search_Employee_by_Nic = ec.Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Damage_Controller damage_Controller=new Damage_Controller();
                ArrayList<Damage> searchDamage_byEmployeeID = damage_Controller.searchDamage_byEmployeeID(Search_Employee_by_Nic.getEid());
                DefaultTableModel dtm=(DefaultTableModel) tabViewPastDamage.getModel();
                dtm.setRowCount(0);
                for(Damage damage:searchDamage_byEmployeeID){
                    Object[]row={damage.getDamage_Date(),damage.getLost()};
                    dtm.addColumn(row);
                }
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this,"No Employee In System\n"+nic);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InputDamages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void inputdamage() {
        if(textLost.getText() == null) {
            JOptionPane.showMessageDialog(this, "Input Cost Of Damage !");
            textLost.setBorder(new LineBorder(Color.red));
        } else {
            String Damageid = texDamageid.getText();
            String date = textDate.getText();
            String nic = SearchFiEmployeeNic.getText();
            int lost = Integer.parseInt(textLost.getText());
            String description = texDescription.getText();
            
            inputdamage(Damageid,date,nic,lost,description);
        }
    }
}
