/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.salary;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.smsc.other.IdGenerator;
import com.smsc.other.Validation;
import java.util.HashMap;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author smsc
 */
public class Manage_Salary extends javax.swing.JFrame {

    int xmouse;
    int ymouse;
    private String EID;

    /**
     * Creates new form Manage_Salary
     */
    public Manage_Salary() {
        initComponents();
        setLocationRelativeTo(null);
//        try {
//            setid();
//            setDate();
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(Manage_Salary.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }
//    private void setid() throws ClassNotFoundException, SQLException{
//        String newId = IdGenerator.getNewId("Salary", "Sid", "S");
//        texSalaryid.setText(newId);
//    }
    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formatedDate = dateFormat.format(date);
       labDate.setText(formatedDate);
    }
    
    private void getUnionPayment(String eid){
        double unionpayment=0.0;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        texEmployeeNic = new org.jdesktop.swingx.JXSearchField();
        jLabel4 = new javax.swing.JLabel();
        texSalaryid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        texETF = new javax.swing.JTextField();
        texCompanyEPF = new javax.swing.JTextField();
        textAmount = new javax.swing.JTextField();
        texTEXT = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        texNopay = new javax.swing.JTextField();
        texSalaryAdvance = new javax.swing.JTextField();
        texUnionPayment = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        texDamage = new javax.swing.JTextField();
        texLoanPayment = new javax.swing.JTextField();
        texEmployeeEPF = new javax.swing.JTextField();
        texTotalEarning = new javax.swing.JTextField();
        texEarning = new javax.swing.JTextField();
        texExtra = new javax.swing.JTextField();
        texTransport = new javax.swing.JTextField();
        texBonus = new javax.swing.JTextField();
        texOtBonus = new javax.swing.JTextField();
        texAttendanceIncentive = new javax.swing.JTextField();
        texBasicSalary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        btPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btBonus = new javax.swing.JButton();
        texChequeNo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        comboBank = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        texSalaryAmount = new javax.swing.JTextField();
        btUnionPayment = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        texSalaryPaymentID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Salary");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Salary id  :  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 30));

        texEmployeeNic.setSearchMode(org.jdesktop.swingx.JXSearchField.SearchMode.REGULAR);
        texEmployeeNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texEmployeeNicActionPerformed(evt);
            }
        });
        texEmployeeNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texEmployeeNicKeyReleased(evt);
            }
        });
        jPanel1.add(texEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Employee NIC  :  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        texSalaryid.setBackground(new java.awt.Color(0, 153, 204));
        texSalaryid.setEditable(false);
        jPanel1.add(texSalaryid, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 80, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salary info..", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("01.  Basic Salary  :-");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, 650, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("02.  Attendance Incentive  :-");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 320, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("04.  OT Bonus  :-");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("05.  Bonus  :-");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("       Total Earning  :-");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 660, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("06.  Transport  :-");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("07.  Employee Provident Fund  :-");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 480, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("08.  Loan Payment  :-");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 490, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("09.  Damage  :-");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 490, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("10.  Union Payment  :-");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 490, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("11.  Salary Advance  :-");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 490, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("14.  No Pay  :-");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 490, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("       Payment Amount  :-");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 660, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("       Employee Provident Fund  :-");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 350, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("       Employee ETF Contd  :-");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 350, 30));

        texETF.setBackground(new java.awt.Color(0, 153, 204));
        texETF.setEditable(false);
        jPanel3.add(texETF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 170, 30));

        texCompanyEPF.setBackground(new java.awt.Color(0, 153, 204));
        texCompanyEPF.setEditable(false);
        jPanel3.add(texCompanyEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 170, 30));

        textAmount.setBackground(new java.awt.Color(0, 153, 204));
        textAmount.setEditable(false);
        jPanel3.add(textAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 170, 30));

        texTEXT.setBackground(new java.awt.Color(0, 153, 204));
        texTEXT.setEditable(false);
        jPanel3.add(texTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 170, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 10, 420));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 10, 420));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 21, 10, 420));

        texNopay.setBackground(new java.awt.Color(0, 153, 204));
        texNopay.setEditable(false);
        jPanel3.add(texNopay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 170, 30));

        texSalaryAdvance.setBackground(new java.awt.Color(0, 153, 204));
        texSalaryAdvance.setEditable(false);
        jPanel3.add(texSalaryAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 170, 30));

        texUnionPayment.setBackground(new java.awt.Color(0, 153, 204));
        texUnionPayment.setEditable(false);
        jPanel3.add(texUnionPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 21, 20, 190));

        texDamage.setBackground(new java.awt.Color(0, 153, 204));
        texDamage.setEditable(false);
        jPanel3.add(texDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 170, 30));

        texLoanPayment.setBackground(new java.awt.Color(0, 153, 204));
        texLoanPayment.setEditable(false);
        jPanel3.add(texLoanPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 170, 30));

        texEmployeeEPF.setBackground(new java.awt.Color(0, 153, 204));
        texEmployeeEPF.setEditable(false);
        jPanel3.add(texEmployeeEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 170, 30));

        texTotalEarning.setBackground(new java.awt.Color(0, 153, 204));
        texTotalEarning.setEditable(false);
        jPanel3.add(texTotalEarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 170, 30));

        texEarning.setBackground(new java.awt.Color(0, 153, 204));
        texEarning.setEditable(false);
        jPanel3.add(texEarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 170, 30));

        texExtra.setBackground(new java.awt.Color(0, 153, 204));
        texExtra.setEditable(false);
        jPanel3.add(texExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 170, 30));

        texTransport.setBackground(new java.awt.Color(0, 153, 204));
        texTransport.setEditable(false);
        jPanel3.add(texTransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 160, 30));

        texBonus.setBackground(new java.awt.Color(0, 153, 204));
        texBonus.setEditable(false);
        jPanel3.add(texBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 160, 30));

        texOtBonus.setEditable(false);
        texOtBonus.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.add(texOtBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 160, 30));

        texAttendanceIncentive.setBackground(new java.awt.Color(0, 153, 204));
        texAttendanceIncentive.setEditable(false);
        jPanel3.add(texAttendanceIncentive, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 160, 30));

        texBasicSalary.setBackground(new java.awt.Color(0, 153, 204));
        texBasicSalary.setEditable(false);
        jPanel3.add(texBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 170, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 850, 530));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Date  :  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 60, 20));
        jPanel1.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 170, 40));

        btPayment.setBackground(new java.awt.Color(102, 102, 102));
        btPayment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btPayment.setText("Payment");
        btPayment.setBorderPainted(false);
        btPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Manage Slary");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1090, 40));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 102, 153));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1105, 25));

        btBonus.setBackground(new java.awt.Color(102, 102, 102));
        btBonus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btBonus.setText("Input Bonus  To Salary");
        btBonus.setBorderPainted(false);
        btBonus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBonusActionPerformed(evt);
            }
        });
        jPanel1.add(btBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 210, 30));
        jPanel1.add(texChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 190, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Cheque No  :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Bank Name : ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, -1));

        comboBank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BOC", "HNB" }));
        jPanel1.add(comboBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 130, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Salary Payment Amount  :  ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        texSalaryAmount.setBackground(new java.awt.Color(0, 153, 204));
        texSalaryAmount.setEditable(false);
        jPanel1.add(texSalaryAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 160, 30));

        btUnionPayment.setBackground(new java.awt.Color(102, 102, 102));
        btUnionPayment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btUnionPayment.setText("Input Union Payment To Salary");
        btUnionPayment.setBorderPainted(false);
        btUnionPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btUnionPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Salary Payment id  : ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 120, 30));

        texSalaryPaymentID.setBackground(new java.awt.Color(0, 153, 204));
        texSalaryPaymentID.setEditable(false);
        jPanel1.add(texSalaryPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 90, 30));

        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 240, 530));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1105, 712));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaymentActionPerformed
        //printreport();
    }//GEN-LAST:event_btPaymentActionPerformed

    private void texEmployeeNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texEmployeeNicKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(texEmployeeNic);
        }
    }//GEN-LAST:event_texEmployeeNicKeyReleased

    private void texEmployeeNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texEmployeeNicActionPerformed
        setSalary();
        /*try {
            Employee searchEmployee;
            searchEmployee = Salary.searchEmployee(texEmployeeNic.getText());
            if (searchEmployee != null) {
                Employee=searchEmployee.getSurename()+" "+searchEmployee.getLastname();
                EmployeeNIC=searchEmployee.getNic_No();
                Grade searchGrade = searchGrade(searchEmployee.getGid());
                if (searchGrade != null) {
                    texBasicSalary.setText(String.valueOf(searchGrade.getBasic_Salary()));
                    Employee_Expetions_Controller employee_Expetions_Controller=new Employee_Expetions_Controller();
                    Employee_Expetions all = employee_Expetions_Controller.getAll();
                    int noofWorkiningDays = getnoofWorkiningDays(searchEmployee.getEid());
                    String s=null;
                    if (noofWorkiningDays >= 22) {
                            texAttendanceIncentive.setText(String.valueOf(all.getAttendance_Incentive()));
                            s="S";
                    } else {
                        texAttendanceIncentive.setText("0.0");
                        s=null;
                    }
                    double sumofOTBonus = getsumofOTBonus(searchEmployee.getEid());
                    texOtBonus.setText(String.valueOf(sumofOTBonus));
                    int present = getpresent(searchEmployee.getEid());
                    texNoofWorkingDays.setText(String.valueOf(present));
                    
                    double total1;
                    texTransport.setText(String.valueOf(searchGrade.getTransport_Amount()));
                    if (s != null) {
                        double total=all.getAttendance_Incentive()+sumofOTBonus+searchGrade.getTransport_Amount();
                        texExtra.setText(String.valueOf(total));
                        texEarning.setText(String.valueOf(total));
                        total1=searchGrade.getBasic_Salary()+total;
                        texTotalEarning.setText(String.valueOf(total1));
                    }else {
                        double total=sumofOTBonus+searchGrade.getTransport_Amount();
                        texExtra.setText(String.valueOf(total));
                        texEarning.setText(String.valueOf(total));
                        total1=searchGrade.getBasic_Salary()+total;
                        texTotalEarning.setText(String.valueOf(total1));
                    }
                    
                    
                    
                    
                    double empEPF=(searchGrade.getBasic_Salary()/100)*all.getEPFEmployee();
                    texEmployeeEPF.setText(String.valueOf(empEPF));
                    double comEPF=(searchGrade.getBasic_Salary()/100)*all.getEPFCompany();
                    texCompanyEPF.setText(String.valueOf(comEPF));
                    double etf=(searchGrade.getBasic_Salary()/100)*all.getETF();
                    texETF.setText(String.valueOf(etf));
                    
                    double loanPayment = getloanPayment(searchEmployee.getEid());
                    texLoanPayment.setText(String.valueOf(loanPayment));
                    String text1 = texLoanPayment.getText();
                    String loan;
                    if (text1.equals("0.0")) {
                        loan=null;
                    } else {
                        loan="L";
                    }
                    
                    double damagepayment = getDamagepayment(searchEmployee.getEid());
                    texDamage.setText(String.valueOf(damagepayment));
                    String text = texDamage.getText();
                    String damage;
                    if (text.equals("0.0")) {
                        damage=null;
                    } else {
                        damage="D";
                    }
                    
                    Advance_Salary advanceSalary = getAdvanceSalary(searchEmployee.getEid());
                    if (advanceSalary != null) {
                        texSalaryAdvance.setText(String.valueOf(advanceSalary.getAdvance()));
                    }else {
                        texSalaryAdvance.setText("0");
                    }
                    
                    double nopay = getNopay(searchEmployee.getEid());
                    texNopay.setText(String.valueOf(nopay));
                    String text2 = texNopay.getText();
                    String Nopay;
                    if (text2.equals("0.0")) {
                        Nopay=null;
                    } else {
                        Nopay="N";
                    }
                    
                    double total2;
                    if (advanceSalary != null) {
                        total2 = advanceSalary.getAdvance() + nopay + loanPayment + empEPF + damagepayment;
                    } else if (damage != null){
                        total2 =nopay + loanPayment + empEPF + damagepayment;
                    }else if (loan != null) {
                        total2 =nopay + loanPayment + empEPF;
                    }else if (Nopay != null) {
                        total2 =nopay + empEPF;
                    }else {
                        total2 =empEPF;
                    }
                    texTEXT.setText(String.valueOf(total2));
                    
                    
                    double Total=total1-total2;
                    textAmount.setText(String.valueOf(Total));
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date=labDate.getText();
        Attendance = texAttendanceIncentive.getText();
        BasicSalary = texBasicSalary.getText();
        Bonus = texBonus.getText();
        CompanyEPF = texCompanyEPF.getText();
        DamagePayment = texDamage.getText();
        ETF = texETF.getText();
        Earning= texEarning.getText();
        EmployeeEPF = texEmployeeEPF.getText();
        Extra = texExtra.getText();
        LoanPayment = texLoanPayment.getText();
        NoofDalyWorkning = texNoofWorkingDays.getText();
        Nopay = texNopay.getText();
        OT = texOtBonus.getText();
        SalaryAdvance = texSalaryAdvance.getText();
        SalaryID = texSalaryid.getText();
        TEXT = texTEXT.getText();
        TotalEarning = texTotalEarning.getText();
        Transport = texTransport.getText();
        UnionPayment = texUnionPayment.getText();
        SalaryAmount = textAmount.getText();*/
    }//GEN-LAST:event_texEmployeeNicActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Manage_Salary.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBonusActionPerformed
        AddBonusAmount addBonusAmount = new AddBonusAmount(this, true);
        addBonusAmount.setVisible(true);
    }//GEN-LAST:event_btBonusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBonus;
    private javax.swing.JButton btPayment;
    private javax.swing.JButton btUnionPayment;
    private javax.swing.JComboBox comboBank;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labDate;
    private javax.swing.JTextField texAttendanceIncentive;
    private javax.swing.JTextField texBasicSalary;
    private javax.swing.JTextField texBonus;
    private javax.swing.JTextField texChequeNo;
    private javax.swing.JTextField texCompanyEPF;
    private javax.swing.JTextField texDamage;
    private javax.swing.JTextField texETF;
    private javax.swing.JTextField texEarning;
    private javax.swing.JTextField texEmployeeEPF;
    private org.jdesktop.swingx.JXSearchField texEmployeeNic;
    private javax.swing.JTextField texExtra;
    private javax.swing.JTextField texLoanPayment;
    private javax.swing.JTextField texNopay;
    private javax.swing.JTextField texOtBonus;
    private javax.swing.JTextField texSalaryAdvance;
    private javax.swing.JTextField texSalaryAmount;
    private javax.swing.JTextField texSalaryPaymentID;
    private javax.swing.JTextField texSalaryid;
    private javax.swing.JTextField texTEXT;
    private javax.swing.JTextField texTotalEarning;
    private javax.swing.JTextField texTransport;
    private javax.swing.JTextField texUnionPayment;
    private javax.swing.JTextField textAmount;
    // End of variables declaration//GEN-END:variables
    
    public  void bonus(){
        double bonusAmount=new Salary().getBonus_amount();
        texBonus.setText(String.valueOf(bonusAmount));
    }
    
    private void setSalary() {
        try {
            com.smsc.model.Employee searchEmployee = Salary.searchEmployee(texEmployeeNic.getText());
            if (searchEmployee != null) {
                EID = searchEmployee.getEid();
                double employee_BasicSalary = Salary.getEmployee_BasicSalary(texEmployeeNic.getText());
                texBasicSalary.setText(String.valueOf(employee_BasicSalary));
                String date = labDate.getText();
                String year = date.split("-", 0).toString();
                String month = date.split("-", 1).toString();
                String newdate = year + "-" + month;
                double attendanceIncentive = Salary.getAttendanceIncentive(texEmployeeNic.getText(), newdate);
                texAttendanceIncentive.setText(String.valueOf(attendanceIncentive));
                double sumofOTBonus = Salary.getsumofOTBonus(texEmployeeNic.getText(), newdate);
                texOtBonus.setText(String.valueOf(sumofOTBonus));
                double employee_TransportAmount = Salary.getEmployee_TransportAmount(texEmployeeNic.getText());
                texTransport.setText(String.valueOf(employee_TransportAmount));
                double employee_Epf = Salary.getEmployee_Epf(texEmployeeNic.getText());
                texEmployeeEPF.setText(String.valueOf(employee_Epf));
                double company_Epf = Salary.getCompany_Epf(texEmployeeNic.getText());
                texCompanyEPF.setText(String.valueOf(company_Epf));
                double loanPayment = Salary.getloanPayment(texEmployeeNic.getText());
                texLoanPayment.setText(String.valueOf(loanPayment));
                double nopay = Salary.getNopay(EID, texEmployeeNic.getText());
                texNopay.setText(String.valueOf(nopay));
                double advanceSalary = Salary.getAdvanceSalary(EID, newdate);
                texSalaryAdvance.setText(String.valueOf(advanceSalary));
                double damageAmount = Salary.getDamageAmount(EID);
                texDamage.setText(String.valueOf(damageAmount));
                double etf = Salary.getETF(texEmployeeNic.getText());
                texETF.setText(String.valueOf(etf));
            } else {
                System.out.println("jhdsgfhdfsgjhfg");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void printreport() throws JRException {
        HashMap<String,Object> map=new HashMap<String,Object>();
        map.put("Attendance", texAttendanceIncentive.getText());
        map.put("basic", texBasicSalary.getText());
        map.put("bonus", texBonus.getText());
        map.put("", texChequeNo.getText());
        JasperReport compileReport = JasperCompileManager.compileReport(getClass().getResourceAsStream("newReport.jrxml"));
        JasperPrint fillReport = JasperFillManager.fillReport(compileReport, null);
        JasperViewer.viewReport(fillReport, false);
    }
 }
