/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.half_day;

import com.smsc.controller1.Attendance_Contorller;
import com.smsc.controller1.Department_Controller;
import com.smsc.controller1.Department_Details_Controller;
import com.smsc.controller1.Empolyee_Controller;
import com.smsc.controller1.Grade_Controller;
import com.smsc.controller1.HalfDay_Controller;
import com.smsc.controller1.Jobrole_Controller;
import com.smsc.controller1.Jobrole_Details_Controller;
import com.smsc.model.Attendance;
import com.smsc.model.Department;
import com.smsc.model.Department_Detail;
import com.smsc.model.Employee;
import com.smsc.model.Grade;
import com.smsc.model.HalfDay;
import com.smsc.model.Job_Role;
import com.smsc.model.Job_role_Detail;
import com.smsc.other.IdGenerator;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smsc
 */
public class Manage_Employee_HalfDay extends javax.swing.JFrame {
    private final int timeRun=0;
    private String Eid;
    private String Gid;
    private String Did;
    private String Jrid;
    /**
     * Creates new form Manage_Employee_HalfDay
     */
    public Manage_Employee_HalfDay() {
        initComponents();
        setdate();
        settime();
        createid();
        btSearchEmployee.setVisible(false);
        btGetTime.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labEmployeeNic = new javax.swing.JLabel();
        texEmployeeNic = new org.jdesktop.swingx.JXSearchField();
        btSearchEmployee = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labEmployeeGrade = new javax.swing.JLabel();
        texEmployeeGrade = new javax.swing.JTextField();
        texEmployeeDepartment = new javax.swing.JTextField();
        labEmployeeDepartment = new javax.swing.JLabel();
        labEmployeeJobRole = new javax.swing.JLabel();
        texEmployeeJobrole = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labPresentdays = new javax.swing.JLabel();
        texWorkingday = new javax.swing.JTextField();
        texAbsentday = new javax.swing.JTextField();
        labAbsentdays = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        texDate = new javax.swing.JTextField();
        labDate = new javax.swing.JLabel();
        texTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labTodayArrivalTime = new javax.swing.JLabel();
        texTodayArrivalTime = new javax.swing.JTextField();
        labHalfdayTime = new javax.swing.JLabel();
        texHalfdayTime = new javax.swing.JTextField();
        btGetTime = new javax.swing.JButton();
        btCreateHalfDay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labEmployeeNic.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labEmployeeNic.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeNic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmployeeNic.setText("Enter Employee NIC  : ");
        jPanel1.add(labEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, -1));

        texEmployeeNic.setSearchMode(org.jdesktop.swingx.JXSearchField.SearchMode.REGULAR);
        texEmployeeNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texEmployeeNicActionPerformed(evt);
            }
        });
        jPanel1.add(texEmployeeNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 270, 30));

        btSearchEmployee.setBackground(new java.awt.Color(102, 102, 102));
        btSearchEmployee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btSearchEmployee.setText("Search");
        btSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btSearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labEmployeeGrade.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeGrade.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeGrade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeGrade.setText("Employee Grade  : ");
        jPanel3.add(labEmployeeGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 30));

        texEmployeeGrade.setEditable(false);
        texEmployeeGrade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeGrade.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(texEmployeeGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, 30));

        texEmployeeDepartment.setEditable(false);
        texEmployeeDepartment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeDepartment.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(texEmployeeDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, 30));

        labEmployeeDepartment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeDepartment.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeDepartment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeDepartment.setText("Employee Department  : ");
        jPanel3.add(labEmployeeDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        labEmployeeJobRole.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmployeeJobRole.setForeground(new java.awt.Color(0, 0, 102));
        labEmployeeJobRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEmployeeJobRole.setText("Employee Job Role  : ");
        jPanel3.add(labEmployeeJobRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 30));

        texEmployeeJobrole.setEditable(false);
        texEmployeeJobrole.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texEmployeeJobrole.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(texEmployeeJobrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 230, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 440, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Half Day info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPresentdays.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labPresentdays.setForeground(new java.awt.Color(0, 0, 102));
        labPresentdays.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPresentdays.setText("No Of Working Days  : ");
        jPanel4.add(labPresentdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        texWorkingday.setEditable(false);
        texWorkingday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texWorkingday.setForeground(new java.awt.Color(0, 0, 102));
        jPanel4.add(texWorkingday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 30));

        texAbsentday.setEditable(false);
        texAbsentday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        texAbsentday.setForeground(new java.awt.Color(0, 0, 102));
        jPanel4.add(texAbsentday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 30));

        labAbsentdays.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labAbsentdays.setForeground(new java.awt.Color(0, 0, 102));
        labAbsentdays.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labAbsentdays.setText("No Of Absent Days  : ");
        jPanel4.add(labAbsentdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 420, 120));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 890, 10));

        texDate.setEditable(false);
        texDate.setBackground(new java.awt.Color(0, 102, 153));
        texDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texDate.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 180, 30));

        labDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labDate.setForeground(new java.awt.Color(0, 0, 102));
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labDate.setText("Date  : ");
        jPanel1.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        texTime.setEditable(false);
        texTime.setBackground(new java.awt.Color(0, 102, 153));
        texTime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texTime.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(texTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 210, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Time  : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 90, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Half Day Leave info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTodayArrivalTime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labTodayArrivalTime.setForeground(new java.awt.Color(0, 0, 102));
        labTodayArrivalTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTodayArrivalTime.setText("Today Arrival Time  : ");
        jPanel5.add(labTodayArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        texTodayArrivalTime.setEditable(false);
        texTodayArrivalTime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texTodayArrivalTime.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(texTodayArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 30));

        labHalfdayTime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labHalfdayTime.setForeground(new java.awt.Color(0, 0, 102));
        labHalfdayTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labHalfdayTime.setText("Halfday Time  : ");
        jPanel5.add(labHalfdayTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        texHalfdayTime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texHalfdayTime.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(texHalfdayTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 270, 30));

        btGetTime.setBackground(new java.awt.Color(102, 102, 102));
        btGetTime.setText("GetTime");
        btGetTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetTimeActionPerformed(evt);
            }
        });
        jPanel5.add(btGetTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 40));

        btCreateHalfDay.setBackground(new java.awt.Color(102, 102, 102));
        btCreateHalfDay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btCreateHalfDay.setText("Create Leave");
        btCreateHalfDay.setBorderPainted(false);
        btCreateHalfDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCreateHalfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateHalfDayActionPerformed(evt);
            }
        });
        jPanel5.add(btCreateHalfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 870, 120));

        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee Half Day Leaves");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 890, 40));

        jLabel4.setBackground(new java.awt.Color(0, 102, 153));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("ID  : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        texId.setEditable(false);
        texId.setBackground(new java.awt.Color(0, 102, 153));
        texId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texIdActionPerformed(evt);
            }
        });
        jPanel1.add(texId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 28, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchEmployeeActionPerformed
        searchEmployee();
        getleavecount();
    }//GEN-LAST:event_btSearchEmployeeActionPerformed

    private void btGetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetTimeActionPerformed
        getTime();
    }//GEN-LAST:event_btGetTimeActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(Manage_Employee_HalfDay.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void texEmployeeNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texEmployeeNicActionPerformed
        if (btSearchEmployee.isVisible()==false) {
            searchEmployee();
            getleavecount();
        } else {
            btSearchEmployee.doClick();
        }
    }//GEN-LAST:event_texEmployeeNicActionPerformed

    private void texIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texIdActionPerformed

    private void btCreateHalfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateHalfDayActionPerformed
        createHalfDay();
    }//GEN-LAST:event_btCreateHalfDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Employee_HalfDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateHalfDay;
    private javax.swing.JButton btGetTime;
    private javax.swing.JButton btSearchEmployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labAbsentdays;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labEmployeeDepartment;
    private javax.swing.JLabel labEmployeeGrade;
    private javax.swing.JLabel labEmployeeJobRole;
    private javax.swing.JLabel labEmployeeNic;
    private javax.swing.JLabel labHalfdayTime;
    private javax.swing.JLabel labPresentdays;
    private javax.swing.JLabel labTodayArrivalTime;
    private javax.swing.JTextField texAbsentday;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texEmployeeDepartment;
    private javax.swing.JTextField texEmployeeGrade;
    private javax.swing.JTextField texEmployeeJobrole;
    private org.jdesktop.swingx.JXSearchField texEmployeeNic;
    private javax.swing.JTextField texHalfdayTime;
    private javax.swing.JTextField texId;
    private javax.swing.JTextField texTime;
    private javax.swing.JTextField texTodayArrivalTime;
    private javax.swing.JTextField texWorkingday;
    // End of variables declaration//GEN-END:variables

    private void setdate() {
        Date date=new Date();
        SimpleDateFormat dateFormat=new SimpleDateFormat("YYYY-MM-DD");
        String format = dateFormat.format(date);
        texDate.setText(format);
    }

    private void settime() {
        new Thread()
        {
            @Override
            public void run()
            {
                while(timeRun==0){
                    Date d=new Date();
                    SimpleDateFormat dateFormat1=new SimpleDateFormat("HH:mm:ss:aa");
                    String format1 = dateFormat1.format(d);
                    texTime.setText(format1);
                    }
               }
         }.start();
    }

    private void searchEmployee() {
        try {
            String nic = texEmployeeNic.getText();
            Employee Search_Employee_by_Nic = new Empolyee_Controller().Search_Employee_by_Nic(nic);
            if (Search_Employee_by_Nic != null) {
                Eid=Search_Employee_by_Nic.getEid();
                Grade searchGrade_byGradeid = new Grade_Controller().searchGrade_byGradeid(Search_Employee_by_Nic.getGid());
                if (searchGrade_byGradeid != null) {
                    Gid=searchGrade_byGradeid.getGid();
                    Job_role_Detail searchjobrole_details = new Jobrole_Details_Controller().searchjobrole_details(Search_Employee_by_Nic.getEid());
                    if (searchjobrole_details != null) {
                        Job_Role searchjobrole_byjobroleid = new Jobrole_Controller().searchjobrole_byjobroleid(searchjobrole_details.getJrid());
                        if (searchjobrole_byjobroleid != null) {
                            Jrid=searchjobrole_byjobroleid.getJrid();
                            Department_Detail searchDepartment_Detailseid = new Department_Details_Controller().searchDepartment_Detailseid(Search_Employee_by_Nic.getEid());
                            if (searchDepartment_Detailseid != null) {
                                Department search_Department_by_id = new Department_Controller().search_Department_by_id(searchDepartment_Detailseid.getDid());
                                if (search_Department_by_id != null) {
                                    Did=search_Department_by_id.getDid();
                                    texEmployeeDepartment.setText(search_Department_by_id.getName());
                                    texEmployeeGrade.setText(searchGrade_byGradeid.getName());
                                    texEmployeeJobrole.setText(searchjobrole_byjobroleid.getName());
                                } else {
                                    Toolkit.getDefaultToolkit().beep();
                                    JOptionPane.showMessageDialog(this, "No Department Found !!!");
                                }
                            } else {
                                Toolkit.getDefaultToolkit().beep();
                                JOptionPane.showMessageDialog(this, "No Department Found !!!");
                            }
                        } else {
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(this, "No JobRole Found !!!");
                        }
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "No JobRole Found !!!");
                    }
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "No Grade Found !!!");
                }
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Employee Found In INC No !!!"+nic);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getleavecount() {
        String year = texDate.getText().split("-", 0).toString();
        String month = texDate.getText().split("-", 1).toString();
        String date=year+"-"+month+"-";
        int pre=0;
        int abs=0;
        try {
            ArrayList<Attendance> monthAttendance = new Attendance_Contorller().getMonthAttendance(date);
            for(Attendance attendance : monthAttendance){
                if (attendance.getEid().equals(Eid)) {
                    if (attendance.getAttend().equals("Present")) {
                        pre++;
                    } else {
                        abs++;
                    }
                    if (attendance.getDate().equals(texDate.getText())) {
                        texTodayArrivalTime.setText(attendance.getArrival_Time());
                    }
                }
            }
            texWorkingday.setText(String.valueOf(pre));
            texAbsentday.setText(String.valueOf(abs));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getTime() {
        String time = texTime.getText();
        texHalfdayTime.setText(time);
    }

    private void createid() {
        try {
            String newId = IdGenerator.getNewId("Halfday", "Hid", "H");
            texId.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void createHalfDay() {
        String id = texId.getText();
        String date = texDate.getText();
        double today = Double.parseDouble(texTodayArrivalTime.getText());
        double halfday = Double.parseDouble(texHalfdayTime.getText());
        
        HalfDay halfDay=new HalfDay(id, Eid, date, today, halfday);
        try {
            int createHalfDay = new HalfDay_Controller().createHalfDay(halfDay);
            if (createHalfDay > 0) {
                JOptionPane.showMessageDialog(this, "Half Day Leave Create Success !!!");
                createid();
                texAbsentday.setText("");
                texEmployeeDepartment.setText("");
                texEmployeeGrade.setText("");
                texEmployeeJobrole.setText("");
                texEmployeeNic.setText("");
                texHalfdayTime.setText("");
                texTodayArrivalTime.setText("");
                texWorkingday.setText("");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Half Day Leave Create Fail!!! \n Try Again !!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Manage_Employee_HalfDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
