/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.grade;

import com.smsc.controller1.Grade_Controller;
import com.smsc.model.Grade;
import java.awt.Cursor;
import static java.awt.Frame.WAIT_CURSOR;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author smsc
 */
public class search_grade extends javax.swing.JFrame {
 private View_All_Grade all_Grade;
 int xmouse;
 int ymouse;
    /**
     * Creates new form search_grade
     */
    public search_grade() {
        initComponents();
        setLocationRelativeTo(null);
        loadGrade();
        setdate();
        btRemove.setEnabled(false);
        btupdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updategradePanel = new javax.swing.JPanel();
        dwrateLabel = new javax.swing.JLabel();
        texDalyworking = new javax.swing.JTextField();
        texMaxLoanAmount = new javax.swing.JTextField();
        maxloanaLabel = new javax.swing.JLabel();
        transportaLabel = new javax.swing.JLabel();
        texTransportAmount = new javax.swing.JTextField();
        texTraining = new javax.swing.JTextField();
        trainingpLabel = new javax.swing.JLabel();
        nopayrateLabel = new javax.swing.JLabel();
        texNopay = new javax.swing.JTextField();
        texWeekendOt = new javax.swing.JTextField();
        weekendrateLabel = new javax.swing.JLabel();
        weekdayrateLabel = new javax.swing.JLabel();
        texWeekDayOt = new javax.swing.JTextField();
        texBasicSalary = new javax.swing.JTextField();
        basicsalaryLabel = new javax.swing.JLabel();
        btRemove = new javax.swing.JButton();
        viewgradeButton = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        labGradeName1 = new javax.swing.JLabel();
        gidLabel = new javax.swing.JLabel();
        texGradeid = new javax.swing.JTextField();
        labFee5 = new javax.swing.JLabel();
        texTrainingPreiodFee = new javax.swing.JTextField();
        labFee6 = new javax.swing.JLabel();
        txtnopayfee = new javax.swing.JTextField();
        texWeekendotFee = new javax.swing.JTextField();
        labFee7 = new javax.swing.JLabel();
        labFee8 = new javax.swing.JLabel();
        texWeekdayOtfee = new javax.swing.JTextField();
        texLeaves = new javax.swing.JTextField();
        texHalfday = new javax.swing.JTextField();
        labNoofHalfday1 = new javax.swing.JLabel();
        labNoofLeaves1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texDate = new javax.swing.JTextField();
        comboGradeName = new javax.swing.JComboBox();
        texName = new javax.swing.JTextField();
        texaddDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        updategradePanel.setBackground(new java.awt.Color(255, 255, 255));
        updategradePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dwrateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dwrateLabel.setForeground(new java.awt.Color(0, 0, 102));
        dwrateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dwrateLabel.setText("Dalyworking Rate  :  ");
        updategradePanel.add(dwrateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 29));

        texDalyworking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texDalyworking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texDalyworkingActionPerformed(evt);
            }
        });
        updategradePanel.add(texDalyworking, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, -1));

        texMaxLoanAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texMaxLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texMaxLoanAmountActionPerformed(evt);
            }
        });
        updategradePanel.add(texMaxLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, 30));

        maxloanaLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        maxloanaLabel.setForeground(new java.awt.Color(0, 0, 102));
        maxloanaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maxloanaLabel.setText("Maxloan Amount  :  ");
        updategradePanel.add(maxloanaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, 30));

        transportaLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        transportaLabel.setForeground(new java.awt.Color(0, 0, 102));
        transportaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        transportaLabel.setText("Transport Amount  :  ");
        updategradePanel.add(transportaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, 30));

        texTransportAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texTransportAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTransportAmountActionPerformed(evt);
            }
        });
        updategradePanel.add(texTransportAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 230, 30));

        texTraining.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTrainingActionPerformed(evt);
            }
        });
        updategradePanel.add(texTraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 130, 30));

        trainingpLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        trainingpLabel.setForeground(new java.awt.Color(0, 0, 102));
        trainingpLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        trainingpLabel.setText("Training Preiod  :  ");
        updategradePanel.add(trainingpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 30));

        nopayrateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nopayrateLabel.setForeground(new java.awt.Color(0, 0, 102));
        nopayrateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nopayrateLabel.setText("Nopay Rate  :  ");
        updategradePanel.add(nopayrateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 150, 30));

        texNopay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texNopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNopayActionPerformed(evt);
            }
        });
        updategradePanel.add(texNopay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 130, 30));

        texWeekendOt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texWeekendOt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texWeekendOtActionPerformed(evt);
            }
        });
        updategradePanel.add(texWeekendOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 30));

        weekendrateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        weekendrateLabel.setForeground(new java.awt.Color(0, 0, 102));
        weekendrateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        weekendrateLabel.setText("Weekend Ot Rate  :  ");
        updategradePanel.add(weekendrateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 210, 30));

        weekdayrateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        weekdayrateLabel.setForeground(new java.awt.Color(0, 0, 102));
        weekdayrateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        weekdayrateLabel.setText("Weekday Ot Rate  :  ");
        updategradePanel.add(weekdayrateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 30));

        texWeekDayOt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texWeekDayOt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texWeekDayOtActionPerformed(evt);
            }
        });
        updategradePanel.add(texWeekDayOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 130, 30));

        texBasicSalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texBasicSalaryActionPerformed(evt);
            }
        });
        updategradePanel.add(texBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 230, -1));

        basicsalaryLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        basicsalaryLabel.setForeground(new java.awt.Color(0, 0, 102));
        basicsalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        basicsalaryLabel.setText("Basic Salary  : ");
        updategradePanel.add(basicsalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 150, 29));

        btRemove.setBackground(new java.awt.Color(102, 102, 102));
        btRemove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btRemove.setText("Remove Grade");
        btRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });
        updategradePanel.add(btRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 200, 60));

        viewgradeButton.setBackground(new java.awt.Color(102, 102, 102));
        viewgradeButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewgradeButton.setText("View All Grade");
        viewgradeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewgradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewgradeButtonActionPerformed(evt);
            }
        });
        updategradePanel.add(viewgradeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 200, 60));

        btupdate.setBackground(new java.awt.Color(102, 102, 102));
        btupdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btupdate.setText("Update Grade");
        btupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        updategradePanel.add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 200, 60));

        labGradeName1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labGradeName1.setForeground(new java.awt.Color(0, 0, 102));
        labGradeName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labGradeName1.setText("Grade Name  :  ");
        updategradePanel.add(labGradeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 30));

        gidLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        gidLabel.setForeground(new java.awt.Color(0, 0, 102));
        gidLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gidLabel.setText("Grade id  : ");
        updategradePanel.add(gidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 130, 30));

        texGradeid.setEditable(false);
        updategradePanel.add(texGradeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 150, 30));

        labFee5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labFee5.setForeground(new java.awt.Color(0, 0, 102));
        labFee5.setText("Fee");
        updategradePanel.add(labFee5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        texTrainingPreiodFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texTrainingPreiodFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTrainingPreiodFeeActionPerformed(evt);
            }
        });
        updategradePanel.add(texTrainingPreiodFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 80, 30));

        labFee6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labFee6.setForeground(new java.awt.Color(0, 0, 102));
        labFee6.setText("Fee");
        updategradePanel.add(labFee6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        txtnopayfee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtnopayfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnopayfeeActionPerformed(evt);
            }
        });
        updategradePanel.add(txtnopayfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 80, 30));

        texWeekendotFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texWeekendotFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texWeekendotFeeActionPerformed(evt);
            }
        });
        updategradePanel.add(texWeekendotFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 80, 30));

        labFee7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labFee7.setForeground(new java.awt.Color(0, 0, 102));
        labFee7.setText("Fee");
        updategradePanel.add(labFee7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        labFee8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labFee8.setForeground(new java.awt.Color(0, 0, 102));
        labFee8.setText("Fee");
        updategradePanel.add(labFee8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        texWeekdayOtfee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texWeekdayOtfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texWeekdayOtfeeActionPerformed(evt);
            }
        });
        updategradePanel.add(texWeekdayOtfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 80, 30));

        texLeaves.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texLeaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texLeavesActionPerformed(evt);
            }
        });
        updategradePanel.add(texLeaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 190, 30));

        texHalfday.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        texHalfday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texHalfdayActionPerformed(evt);
            }
        });
        updategradePanel.add(texHalfday, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 190, 30));

        labNoofHalfday1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labNoofHalfday1.setForeground(new java.awt.Color(0, 0, 102));
        labNoofHalfday1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNoofHalfday1.setText("No of Halfday Leaves for one Year  : ");
        updategradePanel.add(labNoofHalfday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        labNoofLeaves1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labNoofLeaves1.setForeground(new java.awt.Color(0, 0, 102));
        labNoofLeaves1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNoofLeaves1.setText("No of Leaves for one Year  : ");
        updategradePanel.add(labNoofLeaves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 290, 30));

        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        updategradePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        updategradePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        updategradePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 830, 25));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Grade Input Date  : ");
        updategradePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 200, -1));
        updategradePanel.add(texDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 160, 30));

        comboGradeName.setBackground(new java.awt.Color(102, 102, 102));
        comboGradeName.setEditable(true);
        comboGradeName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGradeNameItemStateChanged(evt);
            }
        });
        updategradePanel.add(comboGradeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, 30));
        updategradePanel.add(texName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, 30));

        texaddDate.setEditable(false);
        updategradePanel.add(texaddDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Change Name  :  ");
        updategradePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search Grades");
        updategradePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 830, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/dunya-donen1.gif"))); // NOI18N
        updategradePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));
        updategradePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 832, 545));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updategradePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(updategradePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texDalyworkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texDalyworkingActionPerformed
        texMaxLoanAmount.requestFocus();
    }//GEN-LAST:event_texDalyworkingActionPerformed

    private void texMaxLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texMaxLoanAmountActionPerformed
        texTransportAmount.requestFocus();
    }//GEN-LAST:event_texMaxLoanAmountActionPerformed

    private void texTransportAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTransportAmountActionPerformed
        texTraining.requestFocus();
    }//GEN-LAST:event_texTransportAmountActionPerformed

    private void texTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTrainingActionPerformed
        texNopay.requestFocus();
    }//GEN-LAST:event_texTrainingActionPerformed

    private void texNopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNopayActionPerformed
        texWeekendOt.requestFocus();
    }//GEN-LAST:event_texNopayActionPerformed

    private void texWeekendOtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texWeekendOtActionPerformed
        texWeekDayOt.requestFocus();
    }//GEN-LAST:event_texWeekendOtActionPerformed

    private void texWeekDayOtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texWeekDayOtActionPerformed
      //        updateButton.setEnabled(true);
    }//GEN-LAST:event_texWeekDayOtActionPerformed

    private void texBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texBasicSalaryActionPerformed
        texDalyworking.requestFocus();
    }//GEN-LAST:event_texBasicSalaryActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        getifdelete();
//        removeGrade();
    }//GEN-LAST:event_btRemoveActionPerformed

    private void viewgradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewgradeButtonActionPerformed
        if (all_Grade==null) {
            all_Grade=new View_All_Grade();
            all_Grade.setVisible(true);
            this.dispose();
        } else {
            all_Grade.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_viewgradeButtonActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
       getifupdate();
        //updateGrade();
    }//GEN-LAST:event_btupdateActionPerformed

    private void texTrainingPreiodFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTrainingPreiodFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texTrainingPreiodFeeActionPerformed

    private void txtnopayfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnopayfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopayfeeActionPerformed

    private void texWeekendotFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texWeekendotFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texWeekendotFeeActionPerformed

    private void texWeekdayOtfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texWeekdayOtfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texWeekdayOtfeeActionPerformed

    private void texLeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texLeavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texLeavesActionPerformed

    private void texHalfdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texHalfdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texHalfdayActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void comboGradeNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGradeNameItemStateChanged
        searchGrade();
    }//GEN-LAST:event_comboGradeNameItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(search_grade.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicsalaryLabel;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox comboGradeName;
    private javax.swing.JLabel dwrateLabel;
    private javax.swing.JLabel gidLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labFee5;
    private javax.swing.JLabel labFee6;
    private javax.swing.JLabel labFee7;
    private javax.swing.JLabel labFee8;
    private javax.swing.JLabel labGradeName1;
    private javax.swing.JLabel labNoofHalfday1;
    private javax.swing.JLabel labNoofLeaves1;
    private javax.swing.JLabel maxloanaLabel;
    private javax.swing.JLabel nopayrateLabel;
    private javax.swing.JTextField texBasicSalary;
    private javax.swing.JTextField texDalyworking;
    private javax.swing.JTextField texDate;
    private javax.swing.JTextField texGradeid;
    private javax.swing.JTextField texHalfday;
    private javax.swing.JTextField texLeaves;
    private javax.swing.JTextField texMaxLoanAmount;
    private javax.swing.JTextField texName;
    private javax.swing.JTextField texNopay;
    private javax.swing.JTextField texTraining;
    private javax.swing.JTextField texTrainingPreiodFee;
    private javax.swing.JTextField texTransportAmount;
    private javax.swing.JTextField texWeekDayOt;
    private javax.swing.JTextField texWeekdayOtfee;
    private javax.swing.JTextField texWeekendOt;
    private javax.swing.JTextField texWeekendotFee;
    private javax.swing.JTextField texaddDate;
    private javax.swing.JLabel trainingpLabel;
    private javax.swing.JLabel transportaLabel;
    private javax.swing.JTextField txtnopayfee;
    private javax.swing.JPanel updategradePanel;
    private javax.swing.JButton viewgradeButton;
    private javax.swing.JLabel weekdayrateLabel;
    private javax.swing.JLabel weekendrateLabel;
    // End of variables declaration//GEN-END:variables

    private void loadGrade() {
     try {
         ArrayList<Grade> allgrades = new Grade_Controller().getAllgrades();
         DefaultComboBoxModel model=(DefaultComboBoxModel) comboGradeName.getModel();
         model.removeAllElements();
         for(Grade grade : allgrades){;
             model.addElement(grade.getName());
         }
         AutoCompleteDecorator.decorate(comboGradeName);
     } catch (ClassNotFoundException | SQLException ex) {
         Logger.getLogger(search_grade.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    private void searchGrade() {
        String gradeName = comboGradeName.getSelectedItem().toString();
            try {
                Grade searchGrade_byGradename = new Grade_Controller().searchGrade_byGradename(gradeName);
                if (searchGrade_byGradename != null) {
                    btRemove.setEnabled(true);
                    btupdate.setEnabled(true);
                    texaddDate.setText(searchGrade_byGradename.getDate());
                    texName.setText(searchGrade_byGradename.getName());
                    texBasicSalary.setText(String.valueOf(searchGrade_byGradename.getBasic_Salary()));
                    texDalyworking.setText(searchGrade_byGradename.getDalyworking_Rate());
                    texGradeid.setText(searchGrade_byGradename.getGid());
                    texHalfday.setText(searchGrade_byGradename.getNo_of_Halfday_Leaves());
                    texLeaves.setText(searchGrade_byGradename.getNo_of_Leaves());
                    texMaxLoanAmount.setText(String.valueOf(searchGrade_byGradename.getMaxloan_Amount()));
                    texNopay.setText(searchGrade_byGradename.getNopay_Rate());
                    txtnopayfee.setText(String.valueOf(searchGrade_byGradename.getNopay_Fee()));
                    texTraining.setText(searchGrade_byGradename.getTraining_Preiod());
                    texTrainingPreiodFee.setText(String.valueOf(searchGrade_byGradename.getTraining_Fee()));
                    texTransportAmount.setText(String.valueOf(searchGrade_byGradename.getTransport_Amount()));
                    texWeekDayOt.setText(searchGrade_byGradename.getWeekday_Ot_Rate());
                    texWeekdayOtfee.setText(String.valueOf(searchGrade_byGradename.getWeekday_ot_Fee()));
                    texWeekendOt.setText(searchGrade_byGradename.getWeekend_Ot_Rate());
                    texWeekendotFee.setText(String.valueOf(searchGrade_byGradename.getWeekend_ot_Fee()));
                } else {
                    //JOptionPane.showMessageDialog(this, "No Grade In System !!!");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(search_grade.class.getName()).log(Level.SEVERE, null, ex);
            }

    }

    private void updateGrade() {
        String date = texDate.getText();
        String name = texName.getText();
        double basicsalary = Double.parseDouble(texBasicSalary.getText());
        String dalyworking = texDalyworking.getText();
        String id = texGradeid.getText();
        String halfDay = texHalfday.getText();
        String leaves = texLeaves.getText();
        double maxLoan = Double.parseDouble(texMaxLoanAmount.getText());
        String nopay = texNopay.getText();
        double nopayfee = Double.parseDouble(txtnopayfee.getText());
        String traning = texTraining.getText();
        double traningfee = Double.parseDouble(texTrainingPreiodFee.getText());
        double transport = Double.parseDouble(texTransportAmount.getText());
        String weekdayot = texWeekDayOt.getText();
        double weekdayOtfee = Double.parseDouble(texWeekdayOtfee.getText());
        String weekendot = texWeekendOt.getText();
        double weekendOtfee = Double.parseDouble(texWeekendotFee.getText());
        
        Grade grade=new Grade(id, name, date, basicsalary, dalyworking, maxLoan, transport, traning, traningfee, nopay, nopayfee, weekendot, weekendOtfee, weekdayot, weekdayOtfee, leaves, leaves);
     try {
            int updateGrade = new Grade_Controller().updateGrade(grade);
            if (updateGrade > 0) {
                JOptionPane.showMessageDialog(this, "Grade Update Success !!!");
                texaddDate.setText("");
                texName.setText("");
                texBasicSalary.setText("");
                texDalyworking.setText("");
                texGradeid.setText("");
                texHalfday.setText("");
                texLeaves.setText("");
                texMaxLoanAmount.setText("");
                texNopay.setText("");
                txtnopayfee.setText("");
                texTraining.setText("");
                texTrainingPreiodFee.setText("");
                texTransportAmount.setText("");
                texWeekDayOt.setText("");
                texWeekdayOtfee.setText("");
                texWeekendOt.setText("");
                texWeekendotFee.setText("");
         } else {
             int x=0;
             for (int i = 0; i < 11; i++) {
                x=x+i;
             }
             while(x==20){
                this.setCursor(new Cursor(WAIT_CURSOR));
             }   
             JOptionPane.showMessageDialog(this, "Grade Update fail !!!\n Please Check You Enter Details and Try Again !!!");
         }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(search_grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setdate() {
        Date date=new Date();
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-DD");
        String format = dateFormat.format(date);
        texDate.setText(format);
    }

    private void removeGrade() {
        String id = texGradeid.getText();
     try {
            int removeGrade = new Grade_Controller().removeGrade(id);
            if (removeGrade > 0) {
                JOptionPane.showMessageDialog(this, "Grade Remove Success !!!");
                texaddDate.setText("");
                texName.setText("");
                texBasicSalary.setText("");
                texDalyworking.setText("");
                texGradeid.setText("");
                texHalfday.setText("");
                texLeaves.setText("");
                texMaxLoanAmount.setText("");
                texNopay.setText("");
                txtnopayfee.setText("");
                texTraining.setText("");
                texTrainingPreiodFee.setText("");
                texTransportAmount.setText("");
                texWeekDayOt.setText("");
                texWeekdayOtfee.setText("");
                texWeekendOt.setText("");
                texWeekendotFee.setText("");
            } else {
                int x=0;
             for (int i = 0; i < 11; i++) {
                x=x+i;
             }
             while(x==20){
                this.setCursor(new Cursor(WAIT_CURSOR));
             }
             JOptionPane.showMessageDialog(this, "Grade Remove Fail !!! \n Try Again !!!!");
            }
     } catch (ClassNotFoundException | SQLException ex) {
         Logger.getLogger(search_grade.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    
    private void getifdelete() {
     int confirm = JOptionPane.showConfirmDialog(this, "Are you want to Remove This Grade ?");
        if (confirm == JOptionPane.YES_OPTION) {
            removeGrade();
        }
    }

    private void getifupdate() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you want to Update This Grade ?");
        if (confirm == JOptionPane.YES_OPTION) {
            updateGrade();
        }
    }
}
