/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smsc.view.grade;

import com.smsc.controller1.Grade_Controller;
import com.smsc.model.Grade;
import com.smsc.view.departmant.input_department;
import com.smsc.view.main.home_page;
import java.awt.Cursor;
import static java.awt.Frame.WAIT_CURSOR;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smsc
 */
public class View_All_Grade extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    private String GID=null;
    /**
     * Creates new form View_All_Grade
     */
    public View_All_Grade() {
        initComponents();
        setLocationRelativeTo(null);
        loadGrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texAddDate = new javax.swing.JTextField();
        texMaxloanAmount = new javax.swing.JTextField();
        texTransportAmount = new javax.swing.JTextField();
        texWeekDayotRate = new javax.swing.JTextField();
        texWeekEndotRate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabViewGrade = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        texWDayFee = new javax.swing.JTextField();
        texWEndFee = new javax.swing.JTextField();
        btUpdateGrade = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        texNoofleaves = new javax.swing.JTextField();
        texNoofhalfday = new javax.swing.JTextField();
        reloadButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Grade", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Date  : ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Maxloan Amount  : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 210, 210, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Transport Amount  : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 250, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Weekend Ot Rate  : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 330, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Weekday Ot Rate  : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, 210, -1));

        texAddDate.setEditable(false);
        texAddDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(texAddDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 200, 180, 30));

        texMaxloanAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(texMaxloanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 210, 270, 30));

        texTransportAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(texTransportAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 250, 270, 30));

        texWeekDayotRate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(texWeekDayotRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 290, 150, 30));

        texWeekEndotRate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(texWeekEndotRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 330, 150, 30));

        tabViewGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grade Name", "Basic Salary", "Dalyworking Rate", "Training Preiod", "Traning Fee", "Nopay Rate", "NopayFee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabViewGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabViewGradeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabViewGrade);
        if (tabViewGrade.getColumnModel().getColumnCount() > 0) {
            tabViewGrade.getColumnModel().getColumn(0).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(1).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(2).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(3).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(4).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(5).setResizable(false);
            tabViewGrade.getColumnModel().getColumn(6).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, 729, 170));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Fee");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Fee");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, 30));
        jPanel2.add(texWDayFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 140, -1));
        jPanel2.add(texWEndFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 140, -1));

        btUpdateGrade.setBackground(new java.awt.Color(102, 102, 102));
        btUpdateGrade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btUpdateGrade.setText("Update");
        btUpdateGrade.setBorderPainted(false);
        btUpdateGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUpdateGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateGradeActionPerformed(evt);
            }
        });
        jPanel2.add(btUpdateGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("No Of Leaves For One Year  : ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("No Of Half Day Leaves For One Year  : ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        jPanel2.add(texNoofleaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 140, -1));
        jPanel2.add(texNoofhalfday, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 770, 490));

        reloadButton.setBackground(new java.awt.Color(102, 102, 102));
        reloadButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        reloadButton.setText("Reload");
        reloadButton.setBorderPainted(false);
        reloadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reloadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 130, 40));

        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btBack.setBackground(new java.awt.Color(102, 102, 102));
        btBack.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btBack.setText("Back");
        btBack.setBorderPainted(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel1.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 102, 153));
        jLabel7.setOpaque(true);
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 792, 25));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("View Grades");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 770, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/back3232.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 7));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 792, 633));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(View_All_Grade.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        loadGrade();
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void tabViewGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabViewGradeMouseClicked
        getValue();
        if (GID != null) {
            setvalue();
        } else {
        }
    }//GEN-LAST:event_tabViewGradeMouseClicked

    private void btUpdateGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateGradeActionPerformed
        getifupdate();
    }//GEN-LAST:event_btUpdateGradeActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        getback();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_All_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_All_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_All_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_All_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_All_Grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btUpdateGrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reloadButton;
    private javax.swing.JTable tabViewGrade;
    private javax.swing.JTextField texAddDate;
    private javax.swing.JTextField texMaxloanAmount;
    private javax.swing.JTextField texNoofhalfday;
    private javax.swing.JTextField texNoofleaves;
    private javax.swing.JTextField texTransportAmount;
    private javax.swing.JTextField texWDayFee;
    private javax.swing.JTextField texWEndFee;
    private javax.swing.JTextField texWeekDayotRate;
    private javax.swing.JTextField texWeekEndotRate;
    // End of variables declaration//GEN-END:variables

    private void loadGrade() {
        try {
            ArrayList<Grade> allgrades = new Grade_Controller().getAllgrades();
            DefaultTableModel dtm=(DefaultTableModel) tabViewGrade.getModel();
            dtm.setRowCount(0);
            for(Grade grade : allgrades){
                Object[] row={grade.getName(),grade.getBasic_Salary(),grade.getDalyworking_Rate(),grade.getTraining_Preiod(),grade.getTraining_Fee(),grade.getNopay_Rate(),grade.getNopay_Fee()};
                dtm.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(View_All_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getValue() {
        int selectedRow = tabViewGrade.getSelectedRow();
        String name = tabViewGrade.getValueAt(selectedRow, 0).toString();
        try {
            Grade searchGrade_byGradename = new Grade_Controller().searchGrade_byGradename(name);
            GID=searchGrade_byGradename.getGid();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(View_All_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setvalue() {
        try {
            Grade searchGrade_byGradeid = new Grade_Controller().searchGrade_byGradeid(GID);
            texAddDate.setText(searchGrade_byGradeid.getDate());
            texMaxloanAmount.setText(String.valueOf(searchGrade_byGradeid.getMaxloan_Amount()));
            texTransportAmount.setText(String.valueOf(searchGrade_byGradeid.getTransport_Amount()));
            texWDayFee.setText(String.valueOf(searchGrade_byGradeid.getWeekday_ot_Fee()));
            texWEndFee.setText(String.valueOf(searchGrade_byGradeid.getWeekend_ot_Fee()));
            texWeekDayotRate.setText(searchGrade_byGradeid.getWeekday_Ot_Rate());
            texWeekEndotRate.setText(searchGrade_byGradeid.getWeekend_Ot_Rate());
            texNoofleaves.setText(searchGrade_byGradeid.getNo_of_Leaves());
            texNoofhalfday.setText(searchGrade_byGradeid.getNo_of_Halfday_Leaves());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(View_All_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void upgrade() {
        double newMaxloan = Double.parseDouble(texMaxloanAmount.getText());
        double newTransport = Double.parseDouble(texTransportAmount.getText());
        String newWeekdayrate = texWeekDayotRate.getText();
        double newWeekdayFee = Double.parseDouble(texWDayFee.getText());
        String newWeekendrate = texWeekEndotRate.getText();
        double newWeekendFee = Double.parseDouble(texWEndFee.getText());
        String newNoofleaves = texNoofleaves.getText();
        String newNoofhalfDay = texNoofhalfday.getText();
        Grade grade=new Grade(newMaxloan, newTransport, newWeekendrate, newWeekendFee, newWeekdayrate, newWeekdayFee, newNoofleaves, newNoofhalfDay);
        try {
            int updateone = new Grade_Controller().updateone(GID,grade);
            if (updateone > 0) {
                JOptionPane.showMessageDialog(this, "Grade Details Update Success !!!");
                texAddDate.setText("");
                texMaxloanAmount.setText("");
                texTransportAmount.setText("");
                texWDayFee.setText("");
                texWEndFee.setText("");
                texWeekDayotRate.setText("");
                texWeekEndotRate.setText("");
                texNoofleaves.setText("");
                texNoofhalfday.setText("");
            } else {
             int x=0;
             for (int i = 0; i < 11; i++) {
                x=x+i;
             }
             while(x==20){
                this.setCursor(new Cursor(WAIT_CURSOR));
             }   
             JOptionPane.showMessageDialog(this, "Grade Update fail !!!\n Please Check You Enter Details and Try Again !!!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(View_All_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void getifupdate() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you want to Update This Grade ?");
        if (confirm == JOptionPane.YES_OPTION) {
            upgrade();
        }
    }
    private void getback() {
        Object[] options = {"Cancel", "Home Page", "Search_Grade"};
                int showOptionDialog = JOptionPane.showOptionDialog(this, "Back to Where ?", "Qustion", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, new ImageIcon("./src/com/smsc/view/photos1/help.PNG"), options, options[0]);
                if (showOptionDialog == 1) {
                    new home_page().setVisible(true);
                    this.dispose();
                } else if (showOptionDialog == 2) {
                    new search_grade().setVisible(true);
                    this.dispose();
                }
        
    }
}
