/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.view.main;

import com.smsc.view.Attendance.Mark_Attendance;
import com.smsc.view.Attendance.Search_Attendance;

/**
 *
 * @author smsc
 */
public class manage_employee_attendance extends javax.swing.JPanel {

    /**
     * Creates new form manage_employee_attendance
     */
    public manage_employee_attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMark = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btsearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btHalf = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btSearchHalf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btViewHalf = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(880, 601));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 601));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 601));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMark.setBackground(new java.awt.Color(51, 204, 255));
        btMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/mark attendance.png"))); // NOI18N
        btMark.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btMark.setBorderPainted(false);
        btMark.setContentAreaFilled(false);
        btMark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMarkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMarkMouseExited(evt);
            }
        });
        jPanel1.add(btMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mark Employee Attendance");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btsearch.setBackground(new java.awt.Color(51, 204, 255));
        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/view/photos/search attendance.png"))); // NOI18N
        btsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btsearch.setBorderPainted(false);
        btsearch.setContentAreaFilled(false);
        btsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btsearchMouseExited(evt);
            }
        });
        jPanel1.add(btsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 10, 260, 250));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Employee Attendance");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        btHalf.setBackground(new java.awt.Color(51, 204, 255));
        btHalf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btHalf.setBorderPainted(false);
        btHalf.setContentAreaFilled(false);
        btHalf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHalf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btHalfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHalfMouseExited(evt);
            }
        });
        jPanel1.add(btHalf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 250));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage Employee Halfday Leaves");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        btSearchHalf.setBackground(new java.awt.Color(51, 204, 255));
        btSearchHalf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btSearchHalf.setBorderPainted(false);
        btSearchHalf.setContentAreaFilled(false);
        btSearchHalf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearchHalf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchHalfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchHalfMouseExited(evt);
            }
        });
        jPanel1.add(btSearchHalf, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 290, 260, 250));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Search Employee Halfday Leaves");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        btViewHalf.setBackground(new java.awt.Color(51, 204, 255));
        btViewHalf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btViewHalf.setBorderPainted(false);
        btViewHalf.setContentAreaFilled(false);
        btViewHalf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btViewHalf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btViewHalfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btViewHalfMouseExited(evt);
            }
        });
        jPanel1.add(btViewHalf, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 290, 260, 250));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View Employee Halfday Leaves");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btMarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMarkMouseEntered
        btMark.setContentAreaFilled(true);
    }//GEN-LAST:event_btMarkMouseEntered

    private void btMarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMarkMouseExited
        btMark.setContentAreaFilled(false);
    }//GEN-LAST:event_btMarkMouseExited

    private void btsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsearchMouseEntered
        btsearch.setContentAreaFilled(true);
    }//GEN-LAST:event_btsearchMouseEntered

    private void btsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsearchMouseExited
        btsearch.setContentAreaFilled(false);
    }//GEN-LAST:event_btsearchMouseExited

    private void btHalfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHalfMouseEntered
        btHalf.setContentAreaFilled(true);
    }//GEN-LAST:event_btHalfMouseEntered

    private void btHalfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHalfMouseExited
        btHalf.setContentAreaFilled(false);
    }//GEN-LAST:event_btHalfMouseExited

    private void btSearchHalfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchHalfMouseEntered
        btSearchHalf.setContentAreaFilled(true);
    }//GEN-LAST:event_btSearchHalfMouseEntered

    private void btSearchHalfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchHalfMouseExited
        btSearchHalf.setContentAreaFilled(false);
    }//GEN-LAST:event_btSearchHalfMouseExited

    private void btViewHalfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btViewHalfMouseEntered
        btViewHalf.setContentAreaFilled(true);
    }//GEN-LAST:event_btViewHalfMouseEntered

    private void btViewHalfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btViewHalfMouseExited
        btViewHalf.setContentAreaFilled(false);
    }//GEN-LAST:event_btViewHalfMouseExited

    private void btMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMarkMouseClicked
        new Mark_Attendance().setVisible(true);
    }//GEN-LAST:event_btMarkMouseClicked

    private void btsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsearchMouseClicked
        new Search_Attendance().setVisible(true);
    }//GEN-LAST:event_btsearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHalf;
    private javax.swing.JButton btMark;
    private javax.swing.JButton btSearchHalf;
    private javax.swing.JButton btViewHalf;
    private javax.swing.JButton btsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
